package com.negocil.negoturismo.admin.feature.travel.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum Country {
    ANDORRA("ad", "Andorra"),
    UNITED_ARAB_EMIRATES("ae", "United Arab Emirates"),
    AFGHANISTAN("af", "Afghanistan"),
    ANTIGUA_AND_BARBUDA("ag", "Antigua and Barbuda"),
    ANGUILLA("ai", "Anguilla"),
    ALBANIA("al", "Albania"),
    ARMENIA("am", "Armenia"),
    ANGOLA("ao", "Angola"),
    ANTARCTICA("aq", "Antarctica"),
    ARGENTINA("ar", "Argentina"),
    AMERICAN_SAMOA("as", "American Samoa"),
    AUSTRIA("at", "Austria"),
    AUSTRALIA("au", "Australia"),
    ARUBA("aw", "Aruba"),
    ALAND_ISLANDS("ax", "Åland Islands"),
    AZERBAIJAN("az", "Azerbaijan"),
    BOSNIA_AND_HERZEGOVINA("ba", "Bosnia and Herzegovina"),
    BARBADOS("bb", "Barbados"),
    BANGLADESH("bd", "Bangladesh"),
    BELGIUM("be", "Belgium"),
    BURKINA_FASO("bf", "Burkina Faso"),
    BULGARIA("bg", "Bulgaria"),
    BAHRAIN("bh", "Bahrain"),
    BURUNDI("bi", "Burundi"),
    BENIN("bj", "Benin"),
    SAINT_BARTHELEMY("bl", "Saint Barthélemy"),
    BERMUDA("bm", "Bermuda"),
    BRUNEI("bn", "Brunei"),
    BOLIVIA("bo", "Bolivia"),
    BONAIRE("bq", "Bonaire"),
    BRAZIL("br", "Brazil"),
    BAHAMAS("bs", "Bahamas"),
    BHUTAN("bt", "Bhutan"),
    BOUVET_ISLAND("bv", "Bouvet Island"),
    BOTSWANA("bw", "Botswana"),
    BELARUS("by", "Belarus"),
    BELIZE("bz", "Belize"),
    CANADA("ca", "Canada"),
    COCOS_ISLANDS("cc", "Cocos Islands"),
    DR_CONGO("cd", "DR Congo"),
    CENTRAL_AFRICAN_REPUBLIC("cf", "Central African Republic"),
    CONGO("cg", "Congo"),
    SWITZERLAND("ch", "Switzerland"),
    COTE_D_IVOIRE("ci", "Côte d'Ivoire"),
    COOK_ISLANDS("ck", "Cook Islands"),
    CHILE("cl", "Chile"),
    CAMEROON("cm", "Cameroon"),
    CHINA("cn", "China"),
    COLOMBIA("co", "Colombia"),
    COSTA_RICA("cr", "Costa Rica"),
    CUBA("cu", "Cuba"),
    CAPE_VERDE("cv", "Cape Verde"),
    CURACAO("cw", "Curaçao"),
    CHRISTMAS_ISLAND("cx", "Christmas Island"),
    CYPRUS("cy", "Cyprus"),
    CZECH_REPUBLIC("cz", "Czech Republic"),
    GERMANY("de", "Germany"),
    DJIBOUTI("dj", "Djibouti"),
    DENMARK("dk", "Denmark"),
    DOMINICA("dm", "Dominica"),
    DOMINICAN_REPUBLIC("do", "Dominican Republic"),
    ALGERIA("dz", "Algeria"),
    ECUADOR("ec", "Ecuador"),
    ESTONIA("ee", "Estonia"),
    EGYPT("eg", "Egypt"),
    ERITREA("er", "Eritrea"),
    SPAIN("es", "Spain"),
    ETHIOPIA("et", "Ethiopia"),
    FINLAND("fi", "Finland"),
    FIJI("fj", "Fiji"),
    FALKLAND_ISLANDS("fk", "Falkland Islands"),
    MICRONESIA("fm", "Micronesia"),
    FAROE_ISLANDS("fo", "Faroe Islands"),
    FRANCE("fr", "France"),
    GABON("ga", "Gabon"),
    UNITED_KINGDOM("gb", "United Kingdom"),
    GRENADA("gd", "Grenada"),
    GEORGIA("ge", "Georgia"),
    FRENCH_GUIANA("gf", "French Guiana"),
    GUERNSEY("gg", "Guernsey"),
    GHANA("gh", "Ghana"),
    GIBRALTAR("gi", "Gibraltar"),
    GREENLAND("gl", "Greenland"),
    GAMBIA("gm", "Gambia"),
    GUINEA("gn", "Guinea"),
    GUADELOUPE("gp", "Guadeloupe"),
    EQUATORIAL_GUINEA("gq", "Equatorial Guinea"),
    GREECE("gr", "Greece"),
    SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS("gs", "South Georgia and the South Sandwich Islands"),
    GUATEMALA("gt", "Guatemala"),
    GUAM("gu", "Guam"),
    GUINEA_BISSAU("gw", "Guinea-Bissau"),
    GUYANA("gy", "Guyana"),
    HONG_KONG("hk", "Hong Kong"),
    HEARD_ISLAND_AND_MCDONALD_ISLANDS("hm", "Heard Island and McDonald Islands"),
    HONDURAS("hn", "Honduras"),
    CROATIA("hr", "Croatia"),
    HAITI("ht", "Haiti"),
    HUNGARY("hu", "Hungary"),
    INDONESIA("id", "Indonesia"),
    IRELAND("ie", "Ireland"),
    ISRAEL("il", "Israel"),
    ISLE_OF_MAN("im", "Isle of Man"),
    INDIA("in", "India"),
    BRITISH_INDIAN_OCEAN_TERRITORY("io", "British Indian Ocean Territory"),
    IRAQ("iq", "Iraq"),
    IRAN("ir", "Iran"),
    ICELAND("is", "Iceland"),
    ITALY("it", "Italy"),
    JERSEY("je", "Jersey"),
    JAMAICA("jm", "Jamaica"),
    JORDAN("jo", "Jordan"),
    JAPAN("jp", "Japan"),
    KENYA("ke", "Kenya"),
    KYRGYZSTAN("kg", "Kyrgyzstan"),
    CAMBODIA("kh", "Cambodia"),
    KIRIBATI("ki", "Kiribati"),
    COMOROS("km", "Comoros"),
    SAINT_KITTS_AND_NEVIS("kn", "Saint Kitts and Nevis"),
    NORTH_KOREA("kp", "North Korea"),
    SOUTH_KOREA("kr", "South Korea"),
    KUWAIT("kw", "Kuwait"),
    CAYMAN_ISLANDS("ky", "Cayman Islands"),
    KAZAKHSTAN("kz", "Kazakhstan"),
    LAOS("la", "Laos"),
    LEBANON("lb", "Lebanon"),
    SAINT_LUCIA("lc", "Saint Lucia"),
    LIECHTENSTEIN("li", "Liechtenstein"),
    SRI_LANKA("lk", "Sri Lanka"),
    LIBERIA("lr", "Liberia"),
    LESOTHO("ls", "Lesotho"),
    LITHUANIA("lt", "Lithuania"),
    LUXEMBOURG("lu", "Luxembourg"),
    LATVIA("lv", "Latvia"),
    LIBYA("ly", "Libya"),
    MOROCCO("ma", "Morocco"),
    MONACO("mc", "Monaco"),
    MOLDOVA("md", "Moldova"),
    MONTENEGRO("me", "Montenegro"),
    SAINT_MARTIN("mf", "Saint Martin"),
    MADAGASCAR("mg", "Madagascar"),
    MARSHALL_ISLANDS("mh", "Marshall Islands"),
    NORTH_MACEDONIA("mk", "North Macedonia"),
    MALI("ml", "Mali"),
    MYANMAR("mm", "Myanmar"),
    MONGOLIA("mn", "Mongolia"),
    MACAU("mo", "Macau"),
    NORTHERN_MARIANA_ISLANDS("mp", "Northern Mariana Islands"),
    MARTINIQUE("mq", "Martinique"),
    MAURITANIA("mr", "Mauritania"),
    MONTSERRAT("ms", "Montserrat"),
    MALTA("mt", "Malta"),
    MAURITIUS("mu", "Mauritius"),
    MALDIVES("mv", "Maldives"),
    MALAWI("mw", "Malawi"),
    MEXICO("mx", "Mexico"),
    MALAYSIA("my", "Malaysia"),
    MOZAMBIQUE("mz", "Mozambique"),
    NAMIBIA("na", "Namibia"),
    NEW_CALEDONIA("nc", "New Caledonia"),
    NIGER("ne", "Niger"),
    NORFOLK_ISLAND("nf", "Norfolk Island"),
    NIGERIA("ng", "Nigeria"),
    NICARAGUA("ni", "Nicaragua"),
    NETHERLANDS("nl", "Netherlands"),
    NORWAY("no", "Norway"),
    NEPAL("np", "Nepal"),
    NAURU("nr", "Nauru"),
    NIUE("nu", "Niue"),
    NEW_ZEALAND("nz", "New Zealand"),
    OMAN("om", "Oman"),
    PANAMA("pa", "Panama"),
    PERU("pe", "Peru"),
    FRENCH_POLYNESIA("pf", "French Polynesia"),
    PAPUA_NEW_GUINEA("pg", "Papua New Guinea"),
    PHILIPPINES("ph", "Philippines"),
    PAKISTAN("pk", "Pakistan"),
    POLAND("pl", "Poland"),
    SAINT_PIERRE_AND_MIQUELON("pm", "Saint Pierre and Miquelon"),
    PITCAIRN_ISLANDS("pn", "Pitcairn Islands"),
    PUERTO_RICO("pr", "Puerto Rico"),
    PALESTINE("ps", "Palestine"),
    PORTUGAL("pt", "Portugal"),
    PALAU("pw", "Palau"),
    PARAGUAY("py", "Paraguay"),
    QATAR("qa", "Qatar"),
    REUNION("re", "Réunion"),
    ROMANIA("ro", "Romania"),
    SERBIA("rs", "Serbia"),
    RUSSIA("ru", "Russia"),
    RWANDA("rw", "Rwanda"),
    SAUDI_ARABIA("sa", "Saudi Arabia"),
    SOLOMON_ISLANDS("sb", "Solomon Islands"),
    SEYCHELLES("sc", "Seychelles"),
    SUDAN("sd", "Sudan"),
    SWEDEN("se", "Sweden"),
    SINGAPORE("sg", "Singapore"),
    SLOVENIA("si", "Slovenia"),
    SLOVAKIA("sk", "Slovakia"),
    SIERRA_LEONE("sl", "Sierra Leone"),
    SAN_MARINO("sm", "San Marino"),
    SENEGAL("sn", "Senegal"),
    SOMALIA("so", "Somalia"),
    SURINAME("sr", "Suriname"),
    SOUTH_SUDAN("ss", "South Sudan"),
    SAO_TOME_AND_PRINCIPE("st", "São Tomé and Príncipe"),
    EL_SALVADOR("sv", "El Salvador"),
    SINT_MAARTEN("sx", "Sint Maarten"),
    SYRIA("sy", "Syria"),
    ESWATINI("sz", "Eswatini"),
    TURKS_AND_CAICOS_ISLANDS("tc", "Turks and Caicos Islands"),
    CHAD("td", "Chad"),
    FRENCH_SOUTHERN_TERRITORIES("tf", "French Southern Territories"),
    TOGO("tg", "Togo"),
    THAILAND("th", "Thailand"),
    TAJIKISTAN("tj", "Tajikistan"),
    TOKELAU("tk", "Tokelau"),
    TIMOR_LESTE("tl", "Timor-Leste"),
    TURKMENISTAN("tm", "Turkmenistan"),
    TUNISIA("tn", "Tunisia"),
    TONGA("to", "Tonga"),
    TURKEY("tr", "Turkey"),
    TRINIDAD_AND_TOBAGO("tt", "Trinidad and Tobago"),
    TUVALU("tv", "Tuvalu"),
    TAIWAN("tw", "Taiwan"),
    TANZANIA("tz", "Tanzania"),
    UKRAINE("ua", "Ukraine"),
    UGANDA("ug", "Uganda"),
    UNITED_STATES("us", "United States"),
    URUGUAY("uy", "Uruguay"),
    UZBEKISTAN("uz", "Uzbekistan"),
    VATICAN_CITY("va", "Vatican City"),
    SAINT_VINCENT_AND_THE_GRENADINES("vc", "Saint Vincent and the Grenadines"),
    VENEZUELA("ve", "Venezuela"),
    BRITISH_VIRGIN_ISLANDS("vg", "British Virgin Islands"),
    U_S_VIRGIN_ISLANDS("vi", "U.S. Virgin Islands"),
    VIETNAM("vn", "Vietnam"),
    VANUATU("vu", "Vanuatu"),
    WALLIS_AND_FUTUNA("wf", "Wallis and Futuna"),
    SAMOA("ws", "Samoa"),
    KOSOVO("xk", "Kosovo"),
    YEMEN("ye", "Yemen"),
    MAYOTTE("yt", "Mayotte"),
    SOUTH_AFRICA("za", "South Africa"),
    ZAMBIA("zm", "Zambia"),
    ZIMBABWE("zw", "Zimbabwe");

    private final String iso;
    private final String name;

    public static Country fromIso(String iso) {
        for (Country country : values()) {
            if (country.iso.equalsIgnoreCase(iso)) {
                return country;
            }
        }
        throw new IllegalArgumentException("Unknown country iso: " + iso);
    }
}
