package com.negocil.negoturismo.admin.feature.travel.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum CountryTranslate {
    ANDORRA(Country.ANDORRA,
            "Andorra",
            "Andorra",
            "Andorra",
            "Andorre",
            "Andorra",
            "Andorra",
            "アンドラ",
            "안도라",
            "安道尔",
            "Андорра",
            "أندورا"),
    UNITED_ARAB_EMIRATES(Country.UNITED_ARAB_EMIRATES,
            "United Arab Emirates",
            "Emirados Árabes Unidos",
            "Emiratos Árabes Unidos",
            "Émirats Arabes Unis",
            "Vereinigte Arabische Emirate",
            "Emirati Arabi Uniti",
            "アラブ首長国連邦",
            "아랍에미리트연합",
            "阿联酋",
            "ОАЭ",
            "الإمارات العربية المتحدة"),
    AFGHANISTAN(Country.AFGHANISTAN,
            "Afghanistan",
            "Afeganistão",
            "Afganistán",
            "Afghanistan",
            "Afghanistan",
            "Afghanistan",
            "アフガニスタン",
            "아프가니스탄",
            "阿富汗",
            "Афганистан",
            "أفغانستان"),
    ANTIGUA_AND_BARBUDA(Country.ANTIGUA_AND_BARBUDA,
            "Antigua and Barbuda",
            "Antígua e Barbuda",
            "Antigua y Barbuda",
            "Antigua-et-Barbuda",
            "Antigua und Barbuda",
            "Antigua e Barbuda",
            "アンティグア・バーブーダ",
            "안티구아 바부다",
            "安提瓜和巴布达",
            "Антигуа и Барбуда",
            "أنتيغوا وباربودا"),
    ANGUILLA(Country.ANGUILLA,
            "Anguilla",
            "Anguila",
            "Anguila",
            "Anguilla",
            "Anguilla",
            "Anguilla",
            "アンギラ",
            "앙길라",
            "安圭拉",
            "Ангилья",
            "أنغويلا"),
    ALBANIA(Country.ALBANIA,
            "Albania",
            "Albânia",
            "Albania",
            "Albanie",
            "Albanien",
            "Albania",
            "アルバニア",
            "알바니아",
            "阿尔巴尼亚",
            "Албания",
            "ألبانيا"),
    ARMENIA(Country.ARMENIA,
            "Armenia",
            "Arménia",
            "Armenia",
            "Arménie",
            "Armenien",
            "Armenia",
            "アルメニア",
            "아르메니아",
            "亚美尼亚",
            "Армения",
            "أرمينيا"),
    ANGOLA(Country.ANGOLA,
            "Angola",
            "Angola",
            "Angola",
            "Angola",
            "Angola",
            "Angola",
            "アンゴラ",
            "앙골라",
            "安哥拉",
            "Ангола",
            "أنغولا"),
    ANTARCTICA(Country.ANTARCTICA,
            "Antarctica",
            "Antártida",
            "Antártida",
            "Antarctique",
            "Antarktis",
            "Antartide",
            "南極",
            "안타티카",
            "南极洲",
            "Антарктида",
            "القارة القطبية الجنوبية"),
    ARGENTINA(Country.ARGENTINA,
            "Argentina",
            "Argentina",
            "Argentina",
            "Argentine",
            "Argentinien",
            "Argentina",
            "アルゼンチン",
            "아르헨티나",
            "阿根廷",
            "Аргентина",
            "الأرجنتين"),
    AMERICAN_SAMOA(Country.AMERICAN_SAMOA,
            "American Samoa",
            "Samoa Americana",
            "Samoa Americana",
            "Samoa américaines",
            "Amerikanisch-Samoa",
            "Samoa Americane",
            "アメリカ領サモア",
            "아메리칸 사모아",
            "美属萨摩亚",
            "Американское Самоа",
            "ساموا الأمريكية"),
    AUSTRIA(Country.AUSTRIA,
            "Austria",
            "Áustria",
            "Austria",
            "Autriche",
            "Österreich",
            "Austria",
            "オーストリア",
            "오스트리아",
            "奥地利",
            "Австрия",
            "النمسا"),
    AUSTRALIA(Country.AUSTRALIA,
            "Australia",
            "Austrália",
            "Australia",
            "Australie",
            "Australien",
            "Australia",
            "オーストラリア",
            "호주",
            "澳大利亚",
            "Австралия",
            "أستراليا"),
    ARUBA(Country.ARUBA,
            "Aruba",
            "Aruba",
            "Aruba",
            "Aruba",
            "Aruba",
            "Aruba",
            "アルバ",
            "아루바",
            "阿鲁巴",
            "Аруба",
            "أروبا"),
    ALAND_ISLANDS(Country.ALAND_ISLANDS,
            "Åland Islands",
            "Ilhas Åland",
            "Islas Åland",
            "Åland",
            "Åland",
            "Isole Åland",
            "オーランド諸島",
            "올란드 제도",
            "奥兰",
            "Аландские острова",
            "جزر أولاند"),
    AZERBAIJAN(Country.AZERBAIJAN,
            "Azerbaijan",
            "Azerbaijão",
            "Azerbaiyán",
            "Azerbaïdjan",
            "Aserbaidschan",
            "Azerbaigian",
            "アゼルバイジャン",
            "아제르바이잔",
            "阿塞拜疆",
            "Азербайджан",
            "أذربيجان"),
    BOSNIA_AND_HERZEGOVINA(Country.BOSNIA_AND_HERZEGOVINA,
            "Bosnia and Herzegovina",
            "Bósnia-Herzegovina",
            "Bosnia y Herzegovina",
            "Bosnie-Herzégovine",
            "Bosnien und Herzegowina",
            "Bosnia ed Erzegovina",
            "ボスニア・ヘルツェゴビナ",
            "보스니아 헤르체고비나",
            "波黑",
            "Босния и Герцеговина",
            "البوسنة والهرسك"),
    BARBADOS(Country.BARBADOS,
            "Barbados",
            "Barbados",
            "Barbados",
            "Barbade",
            "Barbados",
            "Barbados",
            "バルバドス",
            "바베이도스",
            "巴巴多斯",
            "Барбадос",
            "باربادوس"),
    BANGLADESH(Country.BANGLADESH,
            "Bangladesh",
            "Bangladesh",
            "Bangladesh",
            "Bangladesh",
            "Bangladesch",
            "Bangladesh",
            "バングラデシュ",
            "방글라데시",
            "孟加拉国",
            "Бангладеш",
            "بنغلاديش"),
    BELGIUM(Country.BELGIUM,
            "Belgium",
            "Bélgica",
            "Bélgica",
            "Belgique",
            "Belgien",
            "Belgio",
            "ベルギー",
            "벨기에",
            "比利时",
            "Бельгия",
            "بلجيكا"),
    BURKINA_FASO(Country.BURKINA_FASO,
            "Burkina Faso",
            "Burkina Faso",
            "Burkina Faso",
            "Burkina Faso",
            "Burkina Faso",
            "Burkina Faso",
            "ブルキナファソ",
            "부르키나파소",
            "布基纳法索",
            "Буркина-Фасо",
            "بوركينا فاسو"),
    BULGARIA(Country.BULGARIA,
            "Bulgaria",
            "Bulgária",
            "Bulgaria",
            "Bulgarie",
            "Bulgarien",
            "Bulgaria",
            "ブルガリア",
            "불가리아",
            "保加利亚",
            "Болгария",
            "بلغاريا"),
    BAHRAIN(Country.BAHRAIN,
            "Bahrain",
            "Bahrein",
            "Bahrein",
            "Bahreïn",
            "Bahrain",
            "Bahrain",
            "バーレーン",
            "바레인",
            "巴林",
            "Бахрейн",
            "البحرين"),
    BURUNDI(Country.BURUNDI,
            "Burundi",
            "Burundi",
            "Burundi",
            "Burundi",
            "Burundi",
            "Burundi",
            "ブルンジ",
            "부룬디",
            "布隆迪",
            "Бурунди",
            "بوروندي"),
    BENIN(Country.BENIN,
            "Benin",
            "Benim",
            "Benin",
            "Bénin",
            "Benin",
            "Benin",
            "ベナン",
            "베냉",
            "贝宁",
            "Бенин",
            "بنين"),
    SAINT_BARTHELEMY(Country.SAINT_BARTHELEMY,
            "Saint Barthélemy",
            "São Bartolomeu",
            "Saint Barthélemy",
            "Saint-Barthélemy",
            "Saint-Barthélemy",
            "Saint-Barthélemy",
            "サン・バルテルミー",
            "생 바르 텔레 미",
            "圣巴泰勒米",
            "Сен-Бартелеми",
            "سان بارتيلمي"),
    BERMUDA(Country.BERMUDA,
            "Bermuda",
            "Bermudas",
            "Bermudas",
            "Bermudes",
            "Bermuda",
            "Bermuda",
            "バミューダ",
            "버뮤다",
            "百慕大",
            "Бермуды",
            "برمودا"),
    BRUNEI(Country.BRUNEI,
            "Brunei",
            "Brunei",
            "Brunei Darussalam",
            "Brunei Darussalam",
            "Brunei Darussalam",
            "Brunei",
            "ブルネイ・ダルサラーム",
            "브루나이",
            "文莱",
            "Бруней",
            "بروناي"),
    BOLIVIA(Country.BOLIVIA,
            "Bolivia",
            "Bolívia",
            "Bolivia",
            "Bolivie",
            "Bolivien",
            "Bolivia",
            "ボリビア多民族国",
            "볼리비아",
            "玻利维亚",
            "Боливия",
            "بوليفيا"),
    BONAIRE(Country.BONAIRE,
            "Bonaire",
            "Países Baixos Caribenhos",
            "Bonaire, San Eustaquio y Saba",
            "Bonaire, Saint-Eustache et Saba",
            "Bonaire",
            "Isole BES",
            "ボネール、シント・ユースタティウスおよびサバ",
            "보네르,신트유스타티우스,사바",
            "荷兰加勒比区",
            "Бонэйр, Синт-Эстатиус и Саба",
            "الجزر الكاريبية الهولندية"),
    BRAZIL(Country.BRAZIL,
            "Brazil",
            "Brasil",
            "Brasil",
            "Brésil",
            "Brasilien",
            "Brasile",
            "ブラジル",
            "브라질",
            "巴西",
            "Бразилия",
            "البرازيل"),
    BAHAMAS(Country.BAHAMAS,
            "Bahamas",
            "Bahamas",
            "Bahamas",
            "Bahamas",
            "Bahamas",
            "Bahamas",
            "バハマ",
            "바하마",
            "巴哈马",
            "Багамы",
            "باهاماس"),
    BHUTAN(Country.BHUTAN,
            "Bhutan",
            "Butão",
            "Bután",
            "Bhoutan",
            "Bhutan",
            "Bhutan",
            "ブータン",
            "부탄",
            "不丹",
            "Бутан",
            "بوتان"),
    BOUVET_ISLAND(Country.BOUVET_ISLAND,
            "Bouvet Island",
            "Ilha Bouvet",
            "Isla Bouvet",
            "Île Bouvet",
            "Bouvetinsel",
            "Isola Bouvet",
            "ブーベ島",
            "부베섬",
            "布韦岛",
            "Остров Буве",
            "جزيرة بوفيه"),
    BOTSWANA(Country.BOTSWANA,
            "Botswana",
            "Botsuana",
            "Botswana",
            "Botswana",
            "Botswana",
            "Botswana",
            "ボツワナ",
            "보츠와나",
            "博茨瓦纳",
            "Ботсвана",
            "بوتسوانا"),
    BELARUS(Country.BELARUS,
            "Belarus",
            "Bielorrússia",
            "Bielorrusia",
            "Biélorussie",
            "Belarus",
            "Bielorussia",
            "ベラルーシ",
            "벨라루스",
            "白俄罗斯",
            "Беларусь",
            "روسيا البيضاء"),
    BELIZE(Country.BELIZE,
            "Belize",
            "Belize",
            "Belice",
            "Belize",
            "Belize",
            "Belize",
            "ベリーズ",
            "벨리즈",
            "伯利兹",
            "Белиз",
            "بليز"),
    CANADA(Country.CANADA,
            "Canada",
            "Canadá",
            "Canadá",
            "Canada",
            "Kanada",
            "Canada",
            "カナダ",
            "캐나다",
            "加拿大",
            "Канада",
            "كندا"),
    COCOS_ISLANDS(Country.COCOS_ISLANDS,
            "Cocos Islands",
            "Ilhas Cocos (Keeling)",
            "Islas Cocos (Keeling)",
            "Îles Cocos",
            "Kokosinseln",
            "Isole Cocos e Keeling",
            "ココス（キーリング）諸島",
            "코코스 제도",
            "科科斯（基林）群岛",
            "Кокосовые острова",
            "جزر كوكوس"),
    DR_CONGO(Country.DR_CONGO,
            "DR Congo",
            "República Popular do Congo",
            "Congo (República Democrática del)",
            "République démocratique du Congo",
            "Kongo",
            "Repubblica Democratica del Congo",
            "コンゴ民主共和国",
            "콩고 민주 공화국",
            "刚果（金）",
            "Демократическая Республика Конго",
            "جمهورية الكونغو الديمقراطية"),
    CENTRAL_AFRICAN_REPUBLIC(Country.CENTRAL_AFRICAN_REPUBLIC,
            "Central African Republic",
            "República Centro-Africana",
            "República Centroafricana",
            "République Centrafricaine",
            "Zentralafrikanische Republik",
            "Repubblica Centrafricana",
            "中央アフリカ共和国",
            "중앙 아프리카",
            "中非",
            "ЦАР",
            "جمهورية أفريقيا الوسطى"),
    CONGO(Country.CONGO,
            "Congo",
            "República Democrática do Congo",
            "Congo",
            "République du Congo",
            "Republik Kongo",
            "Repubblica del Congo",
            "コンゴ共和国",
            "콩고",
            "刚果（布）",
            "Республика Конго",
            "جمهورية الكونغو"),
    SWITZERLAND(Country.SWITZERLAND,
            "Switzerland",
            "Suíça",
            "Suiza",
            "Suisse",
            "Schweiz",
            "Svizzera",
            "スイス",
            "스위스",
            "瑞士",
            "Швейцария",
            "سويسرا"),
    COTE_D_IVOIRE(Country.COTE_D_IVOIRE,
            "Côte d'Ivoire",
            "Costa do Marfim",
            "Costa de Marfil",
            "Côte-d'Ivoire",
            "Elfenbeinküste",
            "Costa d'Avorio",
            "コートジボワール",
            "코트디부아르",
            "科特迪瓦",
            "Кот-д’Ивуар",
            "ساحل العاج"),
    COOK_ISLANDS(Country.COOK_ISLANDS,
            "Cook Islands",
            "Ilhas Cook",
            "Islas Cook",
            "Îles Cook",
            "Cookinseln",
            "Isole Cook",
            "クック諸島",
            "쿡 제도",
            "库克群岛",
            "Острова Кука",
            "جزر كوك"),
    CHILE(Country.CHILE,
            "Chile",
            "Chile",
            "Chile",
            "Chili",
            "Chile",
            "Cile",
            "チリ",
            "칠레",
            "智利",
            "Чили",
            "تشيلي"),
    CAMEROON(Country.CAMEROON,
            "Cameroon",
            "Camarões",
            "Camerún",
            "Cameroun",
            "Kamerun",
            "Camerun",
            "カメルーン",
            "카메룬",
            "喀麦隆",
            "Камерун",
            "الكاميرون"),
    CHINA(Country.CHINA,
            "China",
            "China",
            "China",
            "Chine",
            "China",
            "Cina",
            "中華人民共和国",
            "중국",
            "中国",
            "КНР (Китайская Народная Республика)",
            "الصين"),
    COLOMBIA(Country.COLOMBIA,
            "Colombia",
            "Colômbia",
            "Colombia",
            "Colombie",
            "Kolumbien",
            "Colombia",
            "コロンビア",
            "콜롬비아",
            "哥伦比亚",
            "Колумбия",
            "كولومبيا"),
    COSTA_RICA(Country.COSTA_RICA,
            "Costa Rica",
            "Costa Rica",
            "Costa Rica",
            "Costa Rica",
            "Costa Rica",
            "Costa Rica",
            "コスタリカ",
            "코스타리카",
            "哥斯达黎加",
            "Коста-Рика",
            "كوستاريكا"),
    CUBA(Country.CUBA,
            "Cuba",
            "Cuba",
            "Cuba",
            "Cuba",
            "Kuba",
            "Cuba",
            "キューバ",
            "쿠바",
            "古巴",
            "Куба",
            "كوبا"),
    CAPE_VERDE(Country.CAPE_VERDE,
            "Cape Verde",
            "Cabo Verde",
            "Cabo Verde",
            "Cap-Vert",
            "Kap Verde",
            "Capo Verde",
            "カーボベルデ",
            "카보 베르데",
            "佛得角",
            "Кабо-Верде",
            "الرأس الأخضر"),
    CURACAO(Country.CURACAO,
            "Curaçao",
            "Curaçao",
            "Curaçao",
            "Curaçao",
            "Curaçao",
            "Curaçao",
            "キュラソー",
            "큐라소",
            "库拉索",
            "Кюрасао",
            "كوراساو"),
    CHRISTMAS_ISLAND(Country.CHRISTMAS_ISLAND,
            "Christmas Island",
            "Ilha de Natal",
            "Isla de Navidad",
            "Île Christmas",
            "Weihnachtsinsel",
            "Isola del Natale",
            "クリスマス島",
            "크리스마스섬",
            "圣诞岛",
            "Остров Рождества",
            "جزيرة عيد الميلاد"),
    CYPRUS(Country.CYPRUS,
            "Cyprus",
            "Chipre",
            "Chipre",
            "Chypre",
            "Zypern",
            "Cipro",
            "キプロス",
            "사이프러스",
            "塞浦路斯",
            "Кипр",
            "قبرص"),
    CZECH_REPUBLIC(Country.CZECH_REPUBLIC,
            "Czech Republic",
            "Chéquia",
            "República Checa",
            "République Tchèque",
            "Tschechische Republik",
            "Repubblica Ceca",
            "チェコ",
            "체코공화국",
            "捷克",
            "Чехия",
            "جمهورية التشيك"),
    GERMANY(Country.GERMANY,
            "Germany",
            "Alemanha",
            "Alemania",
            "Allemagne",
            "Deutschland",
            "Germania",
            "ドイツ",
            "독일",
            "德国",
            "Германия",
            "ألمانيا"),
    DJIBOUTI(Country.DJIBOUTI,
            "Djibouti",
            "Djibouti",
            "Yibuti",
            "Djibouti",
            "Dschibuti",
            "Gibuti",
            "ジブチ",
            "지부티",
            "吉布提",
            "Джибути",
            "جيبوتي"),
    DENMARK(Country.DENMARK,
            "Denmark",
            "Dinamarca",
            "Dinamarca",
            "Danemark",
            "Dänemark",
            "Danimarca",
            "デンマーク",
            "덴마크",
            "丹麦",
            "Дания",
            "الدنمارك"),
    DOMINICA(Country.DOMINICA,
            "Dominica",
            "Dominica",
            "Dominica",
            "Dominique",
            "Dominica",
            "Dominica",
            "ドミニカ国",
            "도미니카 연방",
            "多米尼克",
            "Доминика",
            "دومينيكا"),
    DOMINICAN_REPUBLIC(Country.DOMINICAN_REPUBLIC,
            "Dominican Republic",
            "República Dominicana",
            "República Dominicana",
            "République Dominicaine",
            "Dominikanische Republik",
            "Repubblica Dominicana",
            "ドミニカ共和国",
            "도미니카 공화국",
            "多米尼加",
            "Доминиканская Республика",
            "جمهورية الدومينيكان"),
    ALGERIA(Country.ALGERIA,
            "Algeria",
            "Argélia",
            "Argelia",
            "Algérie",
            "Algerien",
            "Algeria",
            "アルジェリア",
            "알제리",
            "阿尔及利亚",
            "Алжир",
            "الجزائر"),
    ECUADOR(Country.ECUADOR,
            "Ecuador",
            "Equador",
            "Ecuador",
            "Équateur",
            "Ecuador",
            "Ecuador",
            "エクアドル",
            "에콰도르",
            "厄瓜多尔",
            "Эквадор",
            "الإكوادور"),
    ESTONIA(Country.ESTONIA,
            "Estonia",
            "Estónia",
            "Estonia",
            "Estonie",
            "Estland",
            "Estonia",
            "エストニア",
            "에스토니아",
            "爱沙尼亚",
            "Эстония",
            "إستونيا"),
    EGYPT(Country.EGYPT,
            "Egypt",
            "Egito",
            "Egipto",
            "Égypte",
            "Ägypten",
            "Egitto",
            "エジプト",
            "이집트",
            "埃及",
            "Египет",
            "مصر"),
    ERITREA(Country.ERITREA,
            "Eritrea",
            "Eritreia",
            "Eritrea",
            "Érythrée",
            "Eritrea",
            "Eritrea",
            "エリトリア",
            "에리트레아",
            "厄立特里亚",
            "Эритрея",
            "إريتريا"),
    SPAIN(Country.SPAIN,
            "Spain",
            "Espanha",
            "España",
            "Espagne",
            "Spanien",
            "Spagna",
            "スペイン",
            "스페인",
            "西班牙",
            "Испания",
            "إسبانيا"),
    ETHIOPIA(Country.ETHIOPIA,
            "Ethiopia",
            "Etiópia",
            "Etiopía",
            "Éthiopie",
            "Äthiopien",
            "Etiopia",
            "エチオピア",
            "이디오피아",
            "埃塞俄比亚",
            "Эфиопия",
            "إثيوبيا"),
    FINLAND(Country.FINLAND,
            "Finland",
            "Finlândia",
            "Finlandia",
            "Finlande",
            "Finnland",
            "Finlandia",
            "フィンランド",
            "핀란드",
            "芬兰",
            "Финляндия",
            "فنلندا"),
    FIJI(Country.FIJI,
            "Fiji",
            "Fiji",
            "Fiji",
            "Fidji",
            "Fidschi",
            "Figi",
            "フィジー",
            "피지",
            "斐济",
            "Фиджи",
            "فيجي"),
    FALKLAND_ISLANDS(Country.FALKLAND_ISLANDS,
            "Falkland Islands",
            "Ilhas Malvinas",
            "Islas Malvinas",
            "Îles Malouines",
            "Falklandinseln",
            "Isole Falkland",
            "フォークランド（マルビナス）諸島",
            "포클랜드섬",
            "福克兰群岛",
            "Фолклендские острова",
            "جزر فوكلاند"),
    MICRONESIA(Country.MICRONESIA,
            "Micronesia",
            "Micronésia",
            "Micronesia",
            "Micronésie",
            "Mikronesien",
            "Stati Federati di Micronesia",
            "ミクロネシア連邦",
            "미크로네시아",
            "密克罗尼西亚联邦",
            "Микронезия",
            "ولايات ميكرونيسيا المتحدة"),
    FAROE_ISLANDS(Country.FAROE_ISLANDS,
            "Faroe Islands",
            "Ilhas Faroé",
            "Islas Feroe",
            "Îles Féroé",
            "Färöer",
            "Isole Fær Øer",
            "フェロー諸島",
            "페로 군도",
            "法罗群岛",
            "Фареры",
            "جزر فارو"),
    FRANCE(Country.FRANCE,
            "France",
            "França",
            "Francia",
            "France",
            "Frankreich",
            "Francia",
            "フランス",
            "프랑스",
            "法国",
            "Франция",
            "فرنسا"),
    GABON(Country.GABON,
            "Gabon",
            "Gabão",
            "Gabón",
            "Gabon",
            "Gabun",
            "Gabon",
            "ガボン",
            "가봉",
            "加蓬",
            "Габон",
            "الغابون"),
    UNITED_KINGDOM(Country.UNITED_KINGDOM,
            "United Kingdom",
            "Reino Unido",
            "Reino Unido",
            "Royaume-Uni",
            "Vereinigtes Königreich",
            "Regno Unito",
            "イギリス",
            "영국",
            "英国",
            "Великобритания",
            "المملكة المتحدة"),
    GRENADA(Country.GRENADA,
            "Grenada",
            "Granada",
            "Granada",
            "Grenade",
            "Grenada",
            "Grenada",
            "グレナダ",
            "그레나다",
            "格林纳达",
            "Гренада",
            "غرينادا"),
    GEORGIA(Country.GEORGIA,
            "Georgia",
            "Geórgia",
            "Georgia",
            "Géorgie",
            "Georgien",
            "Georgia",
            "ジョージア",
            "그루지아",
            "格鲁吉亚",
            "Грузия",
            "جورجيا"),
    FRENCH_GUIANA(Country.FRENCH_GUIANA,
            "French Guiana",
            "Guiana Francesa",
            "Guayana Francesa",
            "Guyane française",
            "Französisch-Guayana",
            "Guyana Francese",
            "フランス領ギアナ",
            "프랑스령 기아나",
            "法属圭亚那",
            "Гвиана",
            "غويانا الفرنسية"),
    GUERNSEY(Country.GUERNSEY,
            "Guernsey",
            "Guernsey",
            "Guernsey",
            "Guernesey",
            "Guernsey",
            "Guernsey",
            "ガーンジー",
            "건지",
            "根西",
            "Гернси",
            "غيرنزي"),
    GHANA(Country.GHANA,
            "Ghana",
            "Gana",
            "Ghana",
            "Ghana",
            "Ghana",
            "Ghana",
            "ガーナ",
            "가나",
            "加纳",
            "Гана",
            "غانا"),
    GIBRALTAR(Country.GIBRALTAR,
            "Gibraltar",
            "Gibraltar",
            "Gibraltar",
            "Gibraltar",
            "Gibraltar",
            "Gibilterra",
            "ジブラルタル",
            "지브랄타",
            "直布罗陀",
            "Гибралтар",
            "جبل طارق"),
    GREENLAND(Country.GREENLAND,
            "Greenland",
            "Gronelândia",
            "Groenlandia",
            "Groenland",
            "Grönland",
            "Groenlandia",
            "グリーンランド",
            "그린랜드",
            "格陵兰",
            "Гренландия",
            "جرينلاند"),
    GAMBIA(Country.GAMBIA,
            "Gambia",
            "Gâmbia",
            "Gambia",
            "Gambie",
            "Gambia",
            "Gambia",
            "ガンビア",
            "감비아",
            "冈比亚",
            "Гамбия",
            "غامبيا"),
    GUINEA(Country.GUINEA,
            "Guinea",
            "Guiné",
            "Guinea",
            "Guinée",
            "Guinea",
            "Guinea",
            "ギニア",
            "기니",
            "几内亚",
            "Гвинея",
            "غينيا"),
    GUADELOUPE(Country.GUADELOUPE,
            "Guadeloupe",
            "Guadalupe",
            "Guadalupe",
            "Guadeloupe",
            "Guadeloupe",
            "Guadalupa",
            "グアドループ",
            "과들루프",
            "瓜德罗普",
            "Гваделупа",
            "غوادلوب"),
    EQUATORIAL_GUINEA(Country.EQUATORIAL_GUINEA,
            "Equatorial Guinea",
            "Guiné Equatorial",
            "Guinea Ecuatorial",
            "Guinée équatoriale",
            "Äquatorialguinea",
            "Guinea Equatoriale",
            "赤道ギニア",
            "적도 기니",
            "赤道几内亚",
            "Экваториальная Гвинея",
            "غينيا الاستوائية"),
    GREECE(Country.GREECE,
            "Greece",
            "Grécia",
            "Grecia",
            "Grèce",
            "Griechenland",
            "Grecia",
            "ギリシャ",
            "그리스",
            "希腊",
            "Греция",
            "اليونان"),
    SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS(Country.SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS,
            "South Georgia and the South Sandwich Islands",
            "Geórgia do Sul e Ilhas Sandwich do Sul",
            "Georgia del Sur y las Islas Sandwich del Sur",
            "Géorgie du Sud-et-les Îles Sandwich du Sud",
            "Südgeorgien und die Südlichen Sandwichinseln",
            "Georgia del Sud e isole Sandwich meridionali",
            "サウスジョージア・サウスサンドウィッチ諸島",
            "남조지아 군도",
            "南乔治亚和南桑威奇群岛",
            "Южная Георгия и Южные Сандвичевы Острова",
            "جورجيا الجنوبية وجزر ساندويتش الجنوبية"),
    GUATEMALA(Country.GUATEMALA,
            "Guatemala",
            "Guatemala",
            "Guatemala",
            "Guatemala",
            "Guatemala",
            "Guatemala",
            "グアテマラ",
            "과테말라",
            "危地马拉",
            "Гватемала",
            "غواتيمالا"),
    GUAM(Country.GUAM,
            "Guam",
            "Guam",
            "Guam",
            "Guam",
            "Guam",
            "Guam",
            "グアム",
            "괌",
            "关岛",
            "Гуам",
            "غوام"),
    GUINEA_BISSAU(Country.GUINEA_BISSAU,
            "Guinea-Bissau",
            "Guiné-Bissau",
            "Guinea Bissau",
            "Guinée-Bissau",
            "Guinea-Bissau",
            "Guinea-Bissau",
            "ギニアビサウ",
            "기네비쏘",
            "几内亚比绍",
            "Гвинея-Бисау",
            "غينيا بيساو"),
    GUYANA(Country.GUYANA,
            "Guyana",
            "Guiana",
            "Guyana",
            "Guyana",
            "Guyana",
            "Guyana",
            "ガイアナ",
            "가이아나",
            "圭亚那",
            "Гайана",
            "غيانا"),
    HONG_KONG(Country.HONG_KONG,
            "Hong Kong",
            "Hong Kong",
            "Hong Kong",
            "Hong Kong",
            "Hongkong",
            "Hong Kong",
            "香港",
            "홍콩",
            "香港",
            "Гонконг",
            "هونغ كونغ"),
    HEARD_ISLAND_AND_MCDONALD_ISLANDS(Country.HEARD_ISLAND_AND_MCDONALD_ISLANDS,
            "Heard Island and McDonald Islands",
            "Ilha Heard e Ilhas McDonald",
            "Heard e Islas McDonald",
            "Îles Heard-et-MacDonald",
            "Heard und McDonaldinseln",
            "Isole Heard e McDonald",
            "ハード島とマクドナルド諸島",
            "허드 맥도날드 군도",
            "赫德岛和麦克唐纳群岛",
            "Херд и Макдональд",
            "جزيرة هيرد وجزر ماكدونالد"),
    HONDURAS(Country.HONDURAS,
            "Honduras",
            "Honduras",
            "Honduras",
            "Honduras",
            "Honduras",
            "Honduras",
            "ホンジュラス",
            "온두라스",
            "洪都拉斯",
            "Гондурас",
            "هندوراس"),
    CROATIA(Country.CROATIA,
            "Croatia",
            "Croácia",
            "Croacia",
            "Croatie",
            "Kroatien",
            "Croazia",
            "クロアチア",
            "크로아티아",
            "克罗地亚",
            "Хорватия",
            "كرواتيا"),
    HAITI(Country.HAITI,
            "Haiti",
            "Haiti",
            "Haití",
            "Haïti",
            "Haiti",
            "Haiti",
            "ハイチ",
            "아이티",
            "海地",
            "Гаити",
            "هايتي"),
    HUNGARY(Country.HUNGARY,
            "Hungary",
            "Hungria",
            "Hungría",
            "Hongrie",
            "Ungarn",
            "Ungheria",
            "ハンガリー",
            "헝가리",
            "匈牙利",
            "Венгрия",
            "المجر"),
    INDONESIA(Country.INDONESIA,
            "Indonesia",
            "Indonésia",
            "Indonesia",
            "Indonésie",
            "Indonesien",
            "Indonesia",
            "インドネシア",
            "인도네시아",
            "印尼",
            "Индонезия",
            "إندونيسيا"),
    IRELAND(Country.IRELAND,
            "Ireland",
            "Irlanda",
            "Irlanda",
            "Irlande",
            "Irland",
            "Irlanda",
            "アイルランド",
            "아일랜드",
            "爱尔兰",
            "Ирландия",
            "أيرلندا"),
    ISRAEL(Country.ISRAEL,
            "Israel",
            "Israel",
            "Israel",
            "Israël",
            "Israel",
            "Israele",
            "イスラエル",
            "이스라엘",
            "以色列",
            "Израиль",
            "إسرائيل"),
    ISLE_OF_MAN(Country.ISLE_OF_MAN,
            "Isle of Man",
            "Ilha de Man",
            "Isla de Man",
            "Île de Man",
            "Insel Man",
            "Isola di Man",
            "マン島",
            "맨섬",
            "马恩岛",
            "Остров Мэн",
            "جزيرة مان"),
    INDIA(Country.INDIA,
            "India",
            "Índia",
            "India",
            "Inde",
            "Indien",
            "India",
            "インド",
            "인도",
            "印度",
            "Индия",
            "الهند"),
    BRITISH_INDIAN_OCEAN_TERRITORY(Country.BRITISH_INDIAN_OCEAN_TERRITORY,
            "British Indian Ocean Territory",
            "Território Britânico do Oceano Índico",
            "Territorio Británico del Océano Índico",
            "Océan Indien Britannique",
            "Britisches Territorium im Indischen Ozean",
            "Territori Britannici dell'Oceano Indiano",
            "イギリス領インド洋地域",
            "영인도 제도",
            "英属印度洋领地",
            "Британская территория в Индийском океане",
            "إقليم المحيط الهندي البريطاني"),
    IRAQ(Country.IRAQ,
            "Iraq",
            "Iraque",
            "Iraq",
            "Irak",
            "Irak",
            "Iraq",
            "イラク",
            "이라크",
            "伊拉克",
            "Ирак",
            "العراق"),
    IRAN(Country.IRAN,
            "Iran",
            "Irão",
            "Irán",
            "Iran",
            "Iran",
            "Iran",
            "イラン・イスラム共和国",
            "이란",
            "伊朗",
            "Иран",
            "إيران"),
    ICELAND(Country.ICELAND,
            "Iceland",
            "Islândia",
            "Islandia",
            "Islande",
            "Island",
            "Islanda",
            "アイスランド",
            "아이슬란드",
            "冰岛",
            "Исландия",
            "آيسلندا"),
    ITALY(Country.ITALY,
            "Italy",
            "Itália",
            "Italia",
            "Italie",
            "Italien",
            "Italia",
            "イタリア",
            "이탈리아",
            "意大利",
            "Италия",
            "إيطاليا"),
    JERSEY(Country.JERSEY,
            "Jersey",
            "Jersey",
            "Jersey",
            "Jersey",
            "Jersey",
            "Jersey",
            "ジャージー",
            "저지",
            "泽西",
            "Джерси",
            "جيرزي"),
    JAMAICA(Country.JAMAICA,
            "Jamaica",
            "Jamaica",
            "Jamaica",
            "Jamaïque",
            "Jamaika",
            "Giamaica",
            "ジャマイカ",
            "자메이카",
            "牙买加",
            "Ямайка",
            "جامايكا"),
    JORDAN(Country.JORDAN,
            "Jordan",
            "Jordânia",
            "Jordania",
            "Jordanie",
            "Jordanien",
            "Giordania",
            "ヨルダン",
            "요르단",
            "约旦",
            "Иордания",
            "الأردن"),
    JAPAN(Country.JAPAN,
            "Japan",
            "Japão",
            "Japón",
            "Japon",
            "Japan",
            "Giappone",
            "日本",
            "일본",
            "日本",
            "Япония",
            "اليابان"),
    KENYA(Country.KENYA,
            "Kenya",
            "Quénia",
            "Kenia",
            "Kenya",
            "Kenia",
            "Kenya",
            "ケニア",
            "케냐",
            "肯尼亚",
            "Кения",
            "كينيا"),
    KYRGYZSTAN(Country.KYRGYZSTAN,
            "Kyrgyzstan",
            "Quirguistão",
            "Kirguistán",
            "Kirghizistan",
            "Kirgisistan",
            "Kirghizistan",
            "キルギス",
            "키르키즈스탄",
            "吉尔吉斯斯坦",
            "Киргизия",
            "قيرغيزستان"),
    CAMBODIA(Country.CAMBODIA,
            "Cambodia",
            "Camboja",
            "Camboya",
            "Cambodge",
            "Kambodscha",
            "Cambogia",
            "カンボジア",
            "캄보디아",
            "柬埔寨",
            "Камбоджа",
            "كمبوديا"),
    KIRIBATI(Country.KIRIBATI,
            "Kiribati",
            "Quiribati",
            "Kiribati",
            "Kiribati",
            "Kiribati",
            "Kiribati",
            "キリバス",
            "키르바시",
            "基里巴斯",
            "Кирибати",
            "كيريباتي"),
    COMOROS(Country.COMOROS,
            "Comoros",
            "Comores",
            "Comoras",
            "Comores",
            "Komoren",
            "Comore",
            "コモロ",
            "코모로",
            "科摩罗",
            "Коморы",
            "جزر القمر"),
    SAINT_KITTS_AND_NEVIS(Country.SAINT_KITTS_AND_NEVIS,
            "Saint Kitts and Nevis",
            "São Cristóvão e Neves",
            "Saint Kitts y Nevis",
            "Saint-Christophe-et-Niévès",
            "St. Kitts und Nevis",
            "Saint Kitts e Nevis",
            "セントクリストファー・ネイビス",
            "세인트 키츠 네비스",
            "圣基茨和尼维斯",
            "Сент-Китс и Невис",
            "سانت كيتس ونيفيس"),
    NORTH_KOREA(Country.NORTH_KOREA,
            "North Korea",
            "Coreia do Norte",
            "República Popular Democrática de Corea",
            "Corée du Nord",
            "Nordkorea",
            "Corea del Nord",
            "朝鮮民主主義人民共和国",
            "북한",
            "朝鲜",
            "КНДР (Корейская Народно-Демократическая Республика)",
            "كوريا الشمالية"),
    SOUTH_KOREA(Country.SOUTH_KOREA,
            "South Korea",
            "Coreia do Sul",
            "República de Corea",
            "Corée du Sud",
            "Südkorea",
            "Corea del Sud",
            "大韓民国",
            "대한민국",
            "韩国",
            "Республика Корея",
            "كوريا الجنوبية"),
    KUWAIT(Country.KUWAIT,
            "Kuwait",
            "Koweit",
            "Kuwait",
            "Koweït",
            "Kuwait",
            "Kuwait",
            "クウェート",
            "쿠웨이트",
            "科威特",
            "Кувейт",
            "الكويت"),
    CAYMAN_ISLANDS(Country.CAYMAN_ISLANDS,
            "Cayman Islands",
            "Ilhas Caimão",
            "Islas Caimán",
            "Îles Caïmans",
            "Kaimaninseln",
            "Isole Cayman",
            "ケイマン諸島",
            "케이맨섬",
            "开曼群岛",
            "Острова Кайман",
            "جزر كايمان"),
    KAZAKHSTAN(Country.KAZAKHSTAN,
            "Kazakhstan",
            "Cazaquistão",
            "Kazajistán",
            "Kazakhstan",
            "Kasachstan",
            "Kazakistan",
            "カザフスタン",
            "카자흐스탄",
            "哈萨克斯坦",
            "Казахстан",
            "كازاخستان"),
    LAOS(Country.LAOS,
            "Laos",
            "Laos",
            "República Democrática Popular de Lao",
            "Laos",
            "Laos",
            "Laos",
            "ラオス人民民主共和国",
            "라오스",
            "老挝",
            "Лаос",
            "لاوس"),
    LEBANON(Country.LEBANON,
            "Lebanon",
            "Líbano",
            "Líbano",
            "Liban",
            "Libanon",
            "Libano",
            "レバノン",
            "레바논",
            "黎巴嫩",
            "Ливан",
            "لبنان"),
    SAINT_LUCIA(Country.SAINT_LUCIA,
            "Saint Lucia",
            "Santa Lúcia",
            "Santa Lucía",
            "Sainte-Lucie",
            "St. Lucia",
            "Santa Lucia",
            "セントルシア",
            "세인트 루시아",
            "圣卢西亚",
            "Сент-Люсия",
            "سانت لوسيا"),
    LIECHTENSTEIN(Country.LIECHTENSTEIN,
            "Liechtenstein",
            "Liechtenstein",
            "Liechtenstein",
            "Liechtenstein",
            "Liechtenstein",
            "Liechtenstein",
            "リヒテンシュタイン",
            "리히텐슈타인",
            "列支敦士登",
            "Лихтенштейн",
            "ليختنشتاين"),
    SRI_LANKA(Country.SRI_LANKA,
            "Sri Lanka",
            "Sri Lanka",
            "Sri Lanka",
            "Sri Lanka",
            "Sri Lanka",
            "Sri Lanka",
            "スリランカ",
            "스리랑카",
            "斯里兰卡",
            "Шри-Ланка",
            "سريلانكا"),
    LIBERIA(Country.LIBERIA,
            "Liberia",
            "Libéria",
            "Liberia",
            "Libéria",
            "Liberia",
            "Liberia",
            "リベリア",
            "라이베리아",
            "利比里亚",
            "Либерия",
            "ليبيريا"),
    LESOTHO(Country.LESOTHO,
            "Lesotho",
            "Lesoto",
            "Lesoto",
            "Lesotho",
            "Lesotho",
            "Lesotho",
            "レソト",
            "레소토",
            "莱索托",
            "Лесото",
            "ليسوتو"),
    LITHUANIA(Country.LITHUANIA,
            "Lithuania",
            "Lituânia",
            "Lituania",
            "Lituanie",
            "Litauen",
            "Lituania",
            "リトアニア",
            "리투아니아",
            "立陶宛",
            "Литва",
            "ليتوانيا"),
    LUXEMBOURG(Country.LUXEMBOURG,
            "Luxembourg",
            "Luxemburgo",
            "Luxemburgo",
            "Luxembourg",
            "Luxemburg",
            "Lussemburgo",
            "ルクセンブルク",
            "룩셈부르크",
            "卢森堡",
            "Люксембург",
            "لوكسمبورغ"),
    LATVIA(Country.LATVIA,
            "Latvia",
            "Letónia",
            "Letonia",
            "Lettonie",
            "Lettland",
            "Lettonia",
            "ラトビア",
            "라트비아",
            "拉脱维亚",
            "Латвия",
            "لاتفيا"),
    LIBYA(Country.LIBYA,
            "Libya",
            "Líbia",
            "Libia",
            "Libye",
            "Libyen",
            "Libia",
            "リビア",
            "리비아",
            "利比亚",
            "Ливия",
            "ليبيا"),
    MOROCCO(Country.MOROCCO,
            "Morocco",
            "Marrocos",
            "Marruecos",
            "Maroc",
            "Marokko",
            "Marocco",
            "モロッコ",
            "모로코",
            "摩洛哥",
            "Марокко",
            "المغرب"),
    MONACO(Country.MONACO,
            "Monaco",
            "Mónaco",
            "Mónaco",
            "Monaco",
            "Monaco",
            "Monaco",
            "モナコ",
            "모나코",
            "摩纳哥",
            "Монако",
            "موناكو"),
    MOLDOVA(Country.MOLDOVA,
            "Moldova",
            "Moldávia",
            "Moldavia",
            "Moldavie",
            "Moldawien",
            "Moldavia",
            "モルドバ共和国",
            "몰도바",
            "摩尔多瓦",
            "Молдавия",
            "مولدوفا"),
    MONTENEGRO(Country.MONTENEGRO,
            "Montenegro",
            "Montenegro",
            "Montenegro",
            "Monténégro",
            "Montenegro",
            "Montenegro",
            "モンテネグロ",
            "몬테네그로",
            "黑山",
            "Черногория",
            "الجبل الأسود"),
    SAINT_MARTIN(Country.SAINT_MARTIN,
            "Saint Martin",
            "São Martinho",
            "Saint Martin (francesa)",
            "Saint-Martin (partie française)",
            "Saint-Martin",
            "Saint-Martin",
            "サン・マルタン（フランス領）",
            "세인트 마틴 (프랑스어 부분)",
            "法属圣马丁",
            "Сен-Мартен",
            "سانت مارتن (الجزء الفرنسي)"),
    MADAGASCAR(Country.MADAGASCAR,
            "Madagascar",
            "Madagáscar",
            "Madagascar",
            "Madagascar",
            "Madagaskar",
            "Madagascar",
            "マダガスカル",
            "마다가스카르",
            "马达加斯加",
            "Мадагаскар",
            "مدغشقر"),
    MARSHALL_ISLANDS(Country.MARSHALL_ISLANDS,
            "Marshall Islands",
            "Ilhas Marshall",
            "Islas Marshall",
            "Îles Marshall",
            "Marshallinseln",
            "Isole Marshall",
            "マーシャル諸島",
            "마샬군도",
            "马绍尔群岛",
            "Маршалловы Острова",
            "جزر مارشال"),
    NORTH_MACEDONIA(Country.NORTH_MACEDONIA,
            "North Macedonia",
            "Macedónia do Norte",
            "Macedonia del Norte",
            "Macédoine du Nord",
            "Nordmazedonien",
            "Macedonia del Nord",
            "北マケドニア",
            "마케도니아",
            "北马其顿",
            "Северная Македония",
            "مقدونيا الشمالية"),
    MALI(Country.MALI,
            "Mali",
            "Mali",
            "Malí",
            "Mali",
            "Mali",
            "Mali",
            "マリ",
            "말리",
            "马里",
            "Мали",
            "مالي"),
    MYANMAR(Country.MYANMAR,
            "Myanmar",
            "Mianmar (Birmânia)",
            "Myanmar",
            "Myanmar",
            "Myanmar",
            "Birmania  Myanmar",
            "ミャンマー",
            "미얀마",
            "缅甸",
            "Мьянма",
            "بورما"),
    MONGOLIA(Country.MONGOLIA,
            "Mongolia",
            "Mongólia",
            "Mongolia",
            "Mongolie",
            "Mongolei",
            "Mongolia",
            "モンゴル",
            "몽골",
            "蒙古",
            "Монголия",
            "منغوليا"),
    MACAU(Country.MACAU,
            "Macau",
            "Macau",
            "Macao",
            "Macao",
            "Macao",
            "Macao",
            "マカオ",
            "마카오",
            "澳门",
            "Макао",
            "ماكاو"),
    NORTHERN_MARIANA_ISLANDS(Country.NORTHERN_MARIANA_ISLANDS,
            "Northern Mariana Islands",
            "Ilhas Marianas do Norte",
            "Islas Marianas del Norte",
            "Îles Mariannes du Nord",
            "Nördliche Marianen",
            "Isole Marianne Settentrionali",
            "北マリアナ諸島",
            "북마리아나 군도",
            "北马里亚纳群岛",
            "Северные Марианские Острова",
            "جزر ماريانا الشمالية"),
    MARTINIQUE(Country.MARTINIQUE,
            "Martinique",
            "Martinica",
            "Martinica",
            "Martinique",
            "Martinique",
            "Martinica",
            "マルティニーク",
            "마르티니크",
            "马提尼克",
            "Мартиника",
            "مارتينيك"),
    MAURITANIA(Country.MAURITANIA,
            "Mauritania",
            "Mauritânia",
            "Mauritania",
            "Mauritanie",
            "Mauretanien",
            "Mauritania",
            "モーリタニア",
            "모리타니",
            "毛里塔尼亚",
            "Мавритания",
            "موريتانيا"),
    MONTSERRAT(Country.MONTSERRAT,
            "Montserrat",
            "Monserrate",
            "Montserrat",
            "Montserrat",
            "Montserrat",
            "Montserrat",
            "モントセラト",
            "몬트세라트",
            "蒙特塞拉特",
            "Монтсеррат",
            "مونتسرات"),
    MALTA(Country.MALTA,
            "Malta",
            "Malta",
            "Malta",
            "Malte",
            "Malta",
            "Malta",
            "マルタ",
            "몰타",
            "马耳他",
            "Мальта",
            "مالطا"),
    MAURITIUS(Country.MAURITIUS,
            "Mauritius",
            "Maurícia",
            "Mauricio",
            "Maurice",
            "Mauritius",
            "Mauritius",
            "モーリシャス",
            "모리셔스",
            "毛里求斯",
            "Маврикий",
            "موريشيوس"),
    MALDIVES(Country.MALDIVES,
            "Maldives",
            "Maldivas",
            "Maldivas",
            "Maldives",
            "Malediven",
            "Maldive",
            "モルディブ",
            "몰디브",
            "马尔代夫",
            "Мальдивы",
            "جزر المالديف"),
    MALAWI(Country.MALAWI,
            "Malawi",
            "Maláui",
            "Malaui",
            "Malawi",
            "Malawi",
            "Malawi",
            "マラウイ",
            "말라위",
            "马拉维",
            "Малави",
            "مالاوي"),
    MEXICO(Country.MEXICO,
            "Mexico",
            "México",
            "México",
            "Mexique",
            "Mexiko",
            "Messico",
            "メキシコ",
            "멕시코",
            "墨西哥",
            "Мексика",
            "المكسيك"),
    MALAYSIA(Country.MALAYSIA,
            "Malaysia",
            "Malásia",
            "Malasia",
            "Malaisie",
            "Malaysia",
            "Malesia",
            "マレーシア",
            "말레이시아",
            "马来西亚",
            "Малайзия",
            "ماليزيا"),
    MOZAMBIQUE(Country.MOZAMBIQUE,
            "Mozambique",
            "Moçambique",
            "Mozambique",
            "Mozambique",
            "Mosambik",
            "Mozambico",
            "モザンビーク",
            "모잠비크",
            "莫桑比克",
            "Мозамбик",
            "موزمبيق"),
    NAMIBIA(Country.NAMIBIA,
            "Namibia",
            "Namíbia",
            "Namibia",
            "Namibie",
            "Namibia",
            "Namibia",
            "ナミビア",
            "나미비아",
            "纳米比亚",
            "Намибия",
            "ناميبيا"),
    NEW_CALEDONIA(Country.NEW_CALEDONIA,
            "New Caledonia",
            "Nova Caledónia",
            "Nueva Caledonia",
            "Nouvelle-Calédonie",
            "Neukaledonien",
            "Nuova Caledonia",
            "ニューカレドニア",
            "뉴칼레도니아",
            "新喀里多尼亚",
            "Новая Каледония",
            "كاليدونيا الجديدة"),
    NIGER(Country.NIGER,
            "Niger",
            "Níger",
            "Níger",
            "Niger",
            "Niger",
            "Niger",
            "ニジェール",
            "니제르",
            "尼日尔",
            "Нигер",
            "النيجر"),
    NORFOLK_ISLAND(Country.NORFOLK_ISLAND,
            "Norfolk Island",
            "Ilha Norfolk",
            "Isla Norfolk",
            "Île Norfolk",
            "Norfolkinsel",
            "Isola Norfolk",
            "ノーフォーク島",
            "노퍽섬",
            "诺福克岛",
            "Остров Норфолк",
            "جزيرة نورفولك"),
    NIGERIA(Country.NIGERIA,
            "Nigeria",
            "Nigéria",
            "Nigeria",
            "Nigéria",
            "Nigeria",
            "Nigeria",
            "ナイジェリア",
            "나이지리아",
            "尼日利亚",
            "Нигерия",
            "نيجيريا"),
    NICARAGUA(Country.NICARAGUA,
            "Nicaragua",
            "Nicarágua",
            "Nicaragua",
            "Nicaragua",
            "Nicaragua",
            "Nicaragua",
            "ニカラグア",
            "니카라과",
            "尼加拉瓜",
            "Никарагуа",
            "نيكاراغوا"),
    NETHERLANDS(Country.NETHERLANDS,
            "Netherlands",
            "Países Baixos",
            "Países Bajos",
            "Pays-Bas",
            "Niederlande",
            "Paesi Bassi",
            "オランダ",
            "네덜란드",
            "荷兰",
            "Нидерланды",
            "هولندا"),
    NORWAY(Country.NORWAY,
            "Norway",
            "Noruega",
            "Noruega",
            "Norvège",
            "Norwegen",
            "Norvegia",
            "ノルウェー",
            "노르웨이",
            "挪威",
            "Норвегия",
            "النرويج"),
    NEPAL(Country.NEPAL,
            "Nepal",
            "Nepal",
            "Nepal",
            "Népal",
            "Nepal",
            "Nepal",
            "ネパール",
            "네팔",
            "尼泊尔",
            "Непал",
            "نيبال"),
    NAURU(Country.NAURU,
            "Nauru",
            "Nauru",
            "Nauru",
            "Nauru",
            "Nauru",
            "Nauru",
            "ナウル",
            "나우루",
            "瑙鲁",
            "Науру",
            "ناورو"),
    NIUE(Country.NIUE,
            "Niue",
            "Niue",
            "Niue",
            "Niué",
            "Niue",
            "Niue",
            "ニウエ",
            "니우에",
            "纽埃",
            "Ниуэ",
            "نييوي"),
    NEW_ZEALAND(Country.NEW_ZEALAND,
            "New Zealand",
            "Nova Zelândia",
            "Nueva Zelanda",
            "Nouvelle-Zélande",
            "Neuseeland",
            "Nuova Zelanda",
            "ニュージーランド",
            "뉴질랜드",
            "新西兰",
            "Новая Зеландия",
            "نيوزيلندا"),
    OMAN(Country.OMAN,
            "Oman",
            "Omã",
            "Omán",
            "Oman",
            "Oman",
            "Oman",
            "オマーン",
            "오만",
            "阿曼",
            "Оман",
            "عمان"),
    PANAMA(Country.PANAMA,
            "Panama",
            "Panamá",
            "Panamá",
            "Panama",
            "Panama",
            "Panamá",
            "パナマ",
            "파나마",
            "巴拿马",
            "Панама",
            "بنما"),
    PERU(Country.PERU,
            "Peru",
            "Peru",
            "Perú",
            "Pérou",
            "Peru",
            "Perù",
            "ペルー",
            "페루",
            "秘鲁",
            "Перу",
            "بيرو"),
    FRENCH_POLYNESIA(Country.FRENCH_POLYNESIA,
            "French Polynesia",
            "Polinésia Francesa",
            "Polinesia Francesa",
            "Polynésie française",
            "Französisch-Polynesien",
            "Polinesia Francese",
            "フランス領ポリネシア",
            "프랑스령 폴리네시아",
            "法属波利尼西亚",
            "Французская Полинезия",
            "بولينزيا الفرنسية"),
    PAPUA_NEW_GUINEA(Country.PAPUA_NEW_GUINEA,
            "Papua New Guinea",
            "Papua-Nova Guiné",
            "Papua Nueva Guinea",
            "Papouasie-Nouvelle-Guinée",
            "Papua-Neuguinea",
            "Papua Nuova Guinea",
            "パプアニューギニア",
            "파푸아 뉴기니",
            "巴布亚新几内亚",
            "Папуа — Новая Гвинея",
            "بابوا غينيا الجديدة"),
    PHILIPPINES(Country.PHILIPPINES,
            "Philippines",
            "Filipinas",
            "Filipinas",
            "Philippines",
            "Philippinen",
            "Filippine",
            "フィリピン",
            "필리핀",
            "菲律宾",
            "Филиппины",
            "الفلبين"),
    PAKISTAN(Country.PAKISTAN,
            "Pakistan",
            "Paquistão",
            "Pakistán",
            "Pakistan",
            "Pakistan",
            "Pakistan",
            "パキスタン",
            "파키스탄",
            "巴基斯坦",
            "Пакистан",
            "باكستان"),
    POLAND(Country.POLAND,
            "Poland",
            "Polónia",
            "Polonia",
            "Pologne",
            "Polen",
            "Polonia",
            "ポーランド",
            "폴랜드",
            "波兰",
            "Польша",
            "بولندا"),
    SAINT_PIERRE_AND_MIQUELON(Country.SAINT_PIERRE_AND_MIQUELON,
            "Saint Pierre and Miquelon",
            "Saint Pierre e Miquelon",
            "San Pedro y Miquelón",
            "Saint-Pierre-et-Miquelon",
            "Saint-Pierre und Miquelon",
            "Saint Pierre e Miquelon",
            "サンピエール島・ミクロン島",
            "세인트리에르도,미괘론도",
            "圣皮埃尔和密克隆",
            "Сен-Пьер и Микелон",
            "سان بيير وميكلون"),
    PITCAIRN_ISLANDS(Country.PITCAIRN_ISLANDS,
            "Pitcairn Islands",
            "Ilhas Pitcairn",
            "Pitcairn",
            "Îles Pitcairn",
            "Pitcairninseln",
            "Isole Pitcairn",
            "ピトケアン",
            "핏케언 군도",
            "皮特凯恩群岛",
            "Острова Питкэрн",
            "جزر بيتكيرن"),
    PUERTO_RICO(Country.PUERTO_RICO,
            "Puerto Rico",
            "Porto Rico",
            "Puerto Rico",
            "Porto Rico",
            "Puerto Rico",
            "Porto Rico",
            "プエルトリコ",
            "푸에르토리코",
            "波多黎各",
            "Пуэрто-Рико",
            "بورتوريكو"),
    PALESTINE(Country.PALESTINE,
            "Palestine",
            "Territórios palestinos",
            "Palestina",
            "Palestine",
            "Staat Palästina",
            "Stato di Palestina",
            "パレスチナ",
            "팔레스타인",
            "巴勒斯坦",
            "Государство Палестина",
            "فلسطين"),
    PORTUGAL(Country.PORTUGAL,
            "Portugal",
            "Portugal",
            "Portugal",
            "Portugal",
            "Portugal",
            "Portogallo",
            "ポルトガル",
            "포르투칼",
            "葡萄牙",
            "Португалия",
            "البرتغال"),
    PALAU(Country.PALAU,
            "Palau",
            "Palau",
            "Palau",
            "Palaos",
            "Palau",
            "Palau",
            "パラオ",
            "팔라우",
            "帕劳",
            "Палау",
            "بالاو"),
    PARAGUAY(Country.PARAGUAY,
            "Paraguay",
            "Paraguai",
            "Paraguay",
            "Paraguay",
            "Paraguay",
            "Paraguay",
            "パラグアイ",
            "파라과이",
            "巴拉圭",
            "Парагвай",
            "باراغواي"),
    QATAR(Country.QATAR,
            "Qatar",
            "Qatar",
            "Catar",
            "Qatar",
            "Katar",
            "Qatar",
            "カタール",
            "카타르",
            "卡塔尔",
            "Катар",
            "قطر"),
    REUNION(Country.REUNION,
            "Réunion",
            "Reunião",
            "Reunión",
            "Réunion",
            "Réunion",
            "Réunion",
            "レユニオン",
            "리유니온",
            "留尼汪",
            "Реюньон",
            "لا ريونيون"),
    ROMANIA(Country.ROMANIA,
            "Romania",
            "Roménia",
            "Rumanía",
            "Roumanie",
            "Rumänien",
            "Romania",
            "ルーマニア",
            "루마니아",
            "罗马尼亚",
            "Румыния",
            "رومانيا"),
    SERBIA(Country.SERBIA,
            "Serbia",
            "Sérvia",
            "Serbia",
            "Serbie",
            "Serbien",
            "Serbia",
            "セルビア",
            "세르비아",
            "塞尔维亚",
            "Сербия",
            "صربيا"),
    RUSSIA(Country.RUSSIA,
            "Russia",
            "Rússia",
            "Rusia",
            "Russie",
            "Russische Föderation",
            "Russia",
            "ロシア連邦",
            "러시아연방",
            "俄罗斯",
            "Российская Федерация",
            "روسيا"),
    RWANDA(Country.RWANDA,
            "Rwanda",
            "Ruanda",
            "Ruanda",
            "Rwanda",
            "Ruanda",
            "Ruanda",
            "ルワンダ",
            "르완다",
            "卢旺达",
            "Руанда",
            "رواندا"),
    SAUDI_ARABIA(Country.SAUDI_ARABIA,
            "Saudi Arabia",
            "Arábia Saudita",
            "Arabia Saudita",
            "Arabie Saoudite",
            "Saudi-Arabien",
            "Arabia Saudita",
            "サウジアラビア",
            "사우디아라비아",
            "沙特阿拉伯",
            "Саудовская Аравия",
            "السعودية"),
    SOLOMON_ISLANDS(Country.SOLOMON_ISLANDS,
            "Solomon Islands",
            "Ilhas Salomão",
            "Islas Salomón",
            "Îles Salomon",
            "Salomonen",
            "Isole Salomone",
            "ソロモン諸島",
            "솔로몬 아일랜드",
            "所罗门群岛",
            "Соломоновы Острова",
            "جزر سليمان"),
    SEYCHELLES(Country.SEYCHELLES,
            "Seychelles",
            "Seychelles",
            "Seychelles",
            "Seychelles",
            "Seychellen",
            "Seychelles",
            "セーシェル",
            "세이셸",
            "塞舌尔",
            "Сейшельские Острова",
            "سيشل"),
    SUDAN(Country.SUDAN,
            "Sudan",
            "Sudão",
            "Sudán",
            "Soudan",
            "Sudan",
            "Sudan",
            "スーダン",
            "수단",
            "苏丹",
            "Судан",
            "السودان"),
    SWEDEN(Country.SWEDEN,
            "Sweden",
            "Suécia",
            "Suecia",
            "Suède",
            "Schweden",
            "Svezia",
            "スウェーデン",
            "스웨덴",
            "瑞典",
            "Швеция",
            "السويد"),
    SINGAPORE(Country.SINGAPORE,
            "Singapore",
            "Singapura",
            "Singapur",
            "Singapour",
            "Singapur",
            "Singapore",
            "シンガポール",
            "싱가포르",
            "新加坡",
            "Сингапур",
            "سنغافورة"),
    SLOVENIA(Country.SLOVENIA,
            "Slovenia",
            "Eslovénia",
            "Eslovenia",
            "Slovénie",
            "Slowenien",
            "Slovenia",
            "スロベニア",
            "슬로베니아",
            "斯洛文尼亚",
            "Словения",
            "سلوفينيا"),
    SLOVAKIA(Country.SLOVAKIA,
            "Slovakia",
            "Eslováquia",
            "Eslovaquia",
            "Slovaquie",
            "Slowakei",
            "Slovacchia",
            "スロバキア",
            "슬로바키아",
            "斯洛伐克",
            "Словакия",
            "سلوفاكيا"),
    SIERRA_LEONE(Country.SIERRA_LEONE,
            "Sierra Leone",
            "Serra Leoa",
            "Sierra Leona",
            "Sierra Leone",
            "Sierra Leone",
            "Sierra Leone",
            "シエラレオネ",
            "시에라 리온",
            "塞拉利昂",
            "Сьерра-Леоне",
            "سيراليون"),
    SAN_MARINO(Country.SAN_MARINO,
            "San Marino",
            "San Marino",
            "San Marino",
            "Saint-Marin",
            "San Marino",
            "San Marino",
            "サンマリノ",
            "산 마리노",
            "圣马力诺",
            "Сан-Марино",
            "سان مارينو"),
    SENEGAL(Country.SENEGAL,
            "Senegal",
            "Senegal",
            "Senegal",
            "Sénégal",
            "Senegal",
            "Senegal",
            "セネガル",
            "세네갈",
            "塞内加尔",
            "Сенегал",
            "السنغال"),
    SOMALIA(Country.SOMALIA,
            "Somalia",
            "Somália",
            "Somalia",
            "Somalie",
            "Somalia",
            "Somalia",
            "ソマリア",
            "소말리아",
            "索马里",
            "Сомали",
            "الصومال"),
    SURINAME(Country.SURINAME,
            "Suriname",
            "Suriname",
            "Suriname",
            "Suriname",
            "Suriname",
            "Suriname",
            "スリナム",
            "수리남",
            "苏里南",
            "Суринам",
            "سورينام"),
    SOUTH_SUDAN(Country.SOUTH_SUDAN,
            "South Sudan",
            "Sudão do Sul",
            "Sudán del Sur",
            "Soudan du Sud",
            "Südsudan",
            "Sudan del Sud",
            "南スーダン",
            "남수단",
            "南苏丹",
            "Южный Судан",
            "جنوب السودان"),
    SAO_TOME_AND_PRINCIPE(Country.SAO_TOME_AND_PRINCIPE,
            "São Tomé and Príncipe",
            "São Tomé e Príncipe",
            "Santo Tomé y Príncipe",
            "São Tomé-et-Principe",
            "São Tomé und Príncipe",
            "São Tomé e Príncipe",
            "サントメ・プリンシペ",
            "상토메프린시페",
            "圣多美和普林西比",
            "Сан-Томе и Принсипи",
            "ساو تومي وبرينسيب"),
    EL_SALVADOR(Country.EL_SALVADOR,
            "El Salvador",
            "El Salvador",
            "El Salvador",
            "El Salvador",
            "El Salvador",
            "El Salvador",
            "エルサルバドル",
            "엘살바도르",
            "萨尔瓦多",
            "Сальвадор",
            "السلفادور"),
    SINT_MAARTEN(Country.SINT_MAARTEN,
            "Sint Maarten",
            "São Martinho",
            "Sint Maarten (neerlandesa)",
            "Saint-Martin (partie néerlandaise)",
            "Sint Maarten",
            "Sint Maarten",
            "シント・マールテン（オランダ領）",
            "신트마르텐",
            "荷属圣马丁",
            "Синт-Мартен",
            "سانت مارتن (الجزء الهولندي)"),
    SYRIA(Country.SYRIA,
            "Syria",
            "Síria",
            "República Árabe Siria",
            "Syrie",
            "Syrien, Arabische Republik",
            "Siria",
            "シリア・アラブ共和国",
            "시리아",
            "叙利亚",
            "Сирия",
            "سوريا"),
    ESWATINI(Country.ESWATINI,
            "Eswatini",
            "Essuatíni",
            "Esuatini",
            "Royaume d'Eswatini",
            "Eswatini",
            "Eswatini",
            "スワジランド",
            "스와질란드",
            "斯威士兰",
            "Эсватини",
            "سوازيلاند"),
    TURKS_AND_CAICOS_ISLANDS(Country.TURKS_AND_CAICOS_ISLANDS,
            "Turks and Caicos Islands",
            "Ilhas Turcas e Caicos",
            "Islas Turcas y Caicos",
            "Îles Turques-et-Caïques",
            "Turks- und Caicosinseln",
            "Isole Turks e Caicos",
            "タークス・カイコス諸島",
            "터크스",
            "特克斯和凯科斯群岛",
            "Теркс и Кайкос",
            "جزر توركس وكايكوس"),
    CHAD(Country.CHAD,
            "Chad",
            "Chade",
            "Chad",
            "Tchad",
            "Tschad",
            "Ciad",
            "チャド",
            "차드",
            "乍得",
            "Чад",
            "تشاد"),
    FRENCH_SOUTHERN_TERRITORIES(Country.FRENCH_SOUTHERN_TERRITORIES,
            "French Southern Territories",
            "Terras Austrais e Antárticas Francesas",
            "Tierras Australes Francesas",
            "Terres australes françaises",
            "Französische Süd- und Antarktisgebiete",
            "Territori Francesi del Sud",
            "フランス領南方・南極地域",
            "프랑스 남부영토",
            "法属南部领地",
            "Французские Южные и Антарктические Территории",
            "أراض فرنسية جنوبية وأنتارتيكية"),
    TOGO(Country.TOGO,
            "Togo",
            "Togo",
            "Togo",
            "Togo",
            "Togo",
            "Togo",
            "トーゴ",
            "토고",
            "多哥",
            "Того",
            "توغو"),
    THAILAND(Country.THAILAND,
            "Thailand",
            "Tailândia",
            "Tailandia",
            "Thaïlande",
            "Thailand",
            "Thailandia",
            "タイ",
            "태국",
            "泰国",
            "Таиланд",
            "تايلاند"),
    TAJIKISTAN(Country.TAJIKISTAN,
            "Tajikistan",
            "Tajiquistão",
            "Tayikistán",
            "Tadjikistan",
            "Tadschikistan",
            "Tagikistan",
            "タジキスタン",
            "타지키스탄",
            "塔吉克斯坦",
            "Таджикистан",
            "طاجيكستان"),
    TOKELAU(Country.TOKELAU,
            "Tokelau",
            "Tokelau",
            "Tokelau",
            "Tokelau",
            "Tokelau",
            "Tokelau",
            "トケラウ",
            "토켈로",
            "托克劳",
            "Токелау",
            "توكيلاو"),
    TIMOR_LESTE(Country.TIMOR_LESTE,
            "Timor-Leste",
            "Timor-Leste",
            "Timor-Leste",
            "Timor-Leste",
            "Osttimor",
            "Timor Est",
            "東ティモール",
            "동티모르",
            "东帝汶",
            "Восточный Тимор",
            "تيمور الشرقية"),
    TURKMENISTAN(Country.TURKMENISTAN,
            "Turkmenistan",
            "Turquemenistão",
            "Turkmenistán",
            "Turkménistan",
            "Turkmenistan",
            "Turkmenistan",
            "トルクメニスタン",
            "트르크메니스탄",
            "土库曼斯坦",
            "Туркмения",
            "تركمانستان"),
    TUNISIA(Country.TUNISIA,
            "Tunisia",
            "Tunísia",
            "Túnez",
            "Tunisie",
            "Tunesien",
            "Tunisia",
            "チュニジア",
            "튀니지아",
            "突尼斯",
            "Тунис",
            "تونس"),
    TONGA(Country.TONGA,
            "Tonga",
            "Tonga",
            "Tonga",
            "Tonga",
            "Tonga",
            "Tonga",
            "トンガ",
            "통가",
            "汤加",
            "Тонга",
            "تونغا"),
    TURKEY(Country.TURKEY,
            "Turkey",
            "Turquia",
            "Turquía",
            "Turquie",
            "Türkei",
            "Turchia",
            "トルコ",
            "터키",
            "土耳其",
            "Турция",
            "تركيا"),
    TRINIDAD_AND_TOBAGO(Country.TRINIDAD_AND_TOBAGO,
            "Trinidad and Tobago",
            "Trindade e Tobago",
            "Trinidad y Tobago",
            "Trinité-et-Tobago",
            "Trinidad und Tobago",
            "Trinidad e Tobago",
            "トリニダード・トバゴ",
            "트리니다드 토바고",
            "特立尼达和多巴哥",
            "Тринидад и Тобаго",
            "ترينيداد وتوباغو"),
    TUVALU(Country.TUVALU,
            "Tuvalu",
            "Tuvalu",
            "Tuvalu",
            "Tuvalu",
            "Tuvalu",
            "Tuvalu",
            "ツバル",
            "트발루",
            "图瓦卢",
            "Тувалу",
            "توفالو"),
    TAIWAN(Country.TAIWAN,
            "Taiwan",
            "Taiwan",
            "Taiwán",
            "Taïwan",
            "Taiwan",
            "Repubblica di Cina",
            "台湾",
            "중화민국",
            "中国台湾省",
            "Тайвань",
            "تايوان"),
    TANZANIA(Country.TANZANIA,
            "Tanzania",
            "Tanzânia",
            "Tanzania",
            "République unie de Tanzanie",
            "Tansania, Vereinigte Republik",
            "Tanzania",
            "タンザニア",
            "탄자니아",
            "坦桑尼亚",
            "Танзания",
            "تانزانيا"),
    UKRAINE(Country.UKRAINE,
            "Ukraine",
            "Ucrânia",
            "Ucrania",
            "Ukraine",
            "Ukraine",
            "Ucraina",
            "ウクライナ",
            "우크라이나",
            "乌克兰",
            "Украина",
            "أوكرانيا"),
    UGANDA(Country.UGANDA,
            "Uganda",
            "Uganda",
            "Uganda",
            "Ouganda",
            "Uganda",
            "Uganda",
            "ウガンダ",
            "우간다",
            "乌干达",
            "Уганда",
            "أوغندا"),
    UNITED_STATES(Country.UNITED_STATES,
            "United States",
            "Estados Unidos",
            "Estados Unidos",
            "États-Unis d'Amérique",
            "Vereinigte Staaten von Amerika",
            "Stati Uniti d'America",
            "アメリカ合衆国",
            "미국",
            "美国",
            "США",
            "الولايات المتحدة"),
    URUGUAY(Country.URUGUAY,
            "Uruguay",
            "Uruguai",
            "Uruguay",
            "Uruguay",
            "Uruguay",
            "Uruguay",
            "ウルグアイ",
            "우루과이",
            "乌拉圭",
            "Уругвай",
            "الأوروغواي"),
    UZBEKISTAN(Country.UZBEKISTAN,
            "Uzbekistan",
            "Uzbequistão",
            "Uzbekistán",
            "Ouzbékistan",
            "Usbekistan",
            "Uzbekistan",
            "ウズベキスタン",
            "우즈베키스탄",
            "乌兹别克斯坦",
            "Узбекистан",
            "أوزبكستان"),
    VATICAN_CITY(Country.VATICAN_CITY,
            "Vatican City",
            "Santa Sé",
            "Santa Sede",
            "Saint-Siège (Vatican)",
            "Vatikanstadt",
            "Città del Vaticano",
            "バチカン市国",
            "바티칸",
            "梵蒂冈",
            "Ватикан",
            "الفاتيكان"),
    SAINT_VINCENT_AND_THE_GRENADINES(Country.SAINT_VINCENT_AND_THE_GRENADINES,
            "Saint Vincent and the Grenadines",
            "São Vicente e Granadinas",
            "San Vicente y las Granadinas",
            "Saint-Vincent-et-les-Grenadines",
            "St. Vincent und die Grenadinen",
            "Saint Vincent e Grenadine",
            "セントビンセントおよびグレナディーン諸島",
            "세인트 빈센트 그레나딘",
            "圣文森特和格林纳丁斯",
            "Сент-Винсент и Гренадины",
            "سانت فينسنت والغرينادين"),
    VENEZUELA(Country.VENEZUELA,
            "Venezuela",
            "Venezuela",
            "Venezuela",
            "Venezuela",
            "Venezuela",
            "Venezuela",
            "ベネズエラ・ボリバル共和国",
            "베네수엘라",
            "委内瑞拉",
            "Венесуэла",
            "فنزويلا"),
    BRITISH_VIRGIN_ISLANDS(Country.BRITISH_VIRGIN_ISLANDS,
            "British Virgin Islands",
            "Ilhas Virgens Britânicas",
            "Islas Vírgenes británicas",
            "Îles vierges britanniques",
            "Britische Jungferninseln",
            "Isole Vergini Britanniche",
            "イギリス領ヴァージン諸島",
            "영국령 버진아일랜드",
            "英属维尔京群岛",
            "Виргинские Острова (Великобритания)",
            "جزر العذراء البريطانية"),
    U_S_VIRGIN_ISLANDS(Country.U_S_VIRGIN_ISLANDS,
            "U.S. Virgin Islands",
            "Ilhas Virgens Americanas",
            "Islas Vírgenes de los Estados Unidos",
            "Îles vierges américaines",
            "Amerikanische Jungferninseln",
            "Isole Vergini Americane",
            "アメリカ領ヴァージン諸島",
            "미국령 버진아일랜드",
            "美属维尔京群岛",
            "Виргинские Острова (США)",
            "جزر العذراء الأمريكية"),
    VIETNAM(Country.VIETNAM,
            "Vietnam",
            "Vietname",
            "Vietnam",
            "Vietnam",
            "Vietnam",
            "Vietnam",
            "ベトナム",
            "베트남",
            "越南",
            "Вьетнам",
            "فيتنام"),
    VANUATU(Country.VANUATU,
            "Vanuatu",
            "Vanuatu",
            "Vanuatu",
            "Vanuatu",
            "Vanuatu",
            "Vanuatu",
            "バヌアツ",
            "바누아투",
            "瓦努阿图",
            "Вануату",
            "فانواتو"),
    WALLIS_AND_FUTUNA(Country.WALLIS_AND_FUTUNA,
            "Wallis and Futuna",
            "Wallis e Futuna",
            "Wallis y Futuna",
            "Wallis-et-Futuna",
            "Wallis und Futuna",
            "Wallis e Futuna",
            "ウォリス・フツナ",
            "월리스 후트나",
            "瓦利斯和富图纳",
            "Уоллис и Футуна",
            "والس وفوتونا"),
    SAMOA(Country.SAMOA,
            "Samoa",
            "Samoa",
            "Samoa",
            "Samoa",
            "Samoa",
            "Samoa",
            "サモア",
            "사모아",
            "萨摩亚",
            "Самоа",
            "ساموا"),
    KOSOVO(Country.KOSOVO,
            "Kosovo",
            "Kosovo",
            "Kosovo",
            "Kosovo",
            "Kosovo",
            "Kosovo",
            "コソボ",
            "코소보",
            "科索沃",
            "Косово",
            "كوسوفو"),
    YEMEN(Country.YEMEN,
            "Yemen",
            "Iémen",
            "Yemen",
            "Yémen",
            "Jemen",
            "Yemen",
            "イエメン",
            "예멘",
            "也门",
            "Йемен",
            "اليمن"),
    MAYOTTE(Country.MAYOTTE,
            "Mayotte",
            "Mayotte",
            "Mayotte",
            "Mayotte",
            "Mayotte",
            "Mayotte",
            "マヨット",
            "마요트",
            "马约特",
            "Майотта",
            "مايوت"),
    SOUTH_AFRICA(Country.SOUTH_AFRICA,
            "South Africa",
            "África do Sul",
            "Sudáfrica",
            "Afrique du Sud",
            "Südafrika",
            "Sudafrica",
            "南アフリカ",
            "남아프리카",
            "南非",
            "ЮАР",
            "جنوب أفريقيا"),
    ZAMBIA(Country.ZAMBIA,
            "Zambia",
            "Zâmbia",
            "Zambia",
            "Zambie",
            "Sambia",
            "Zambia",
            "ザンビア",
            "잠비아",
            "赞比亚",
            "Замбия",
            "زامبيا"),
    ZIMBABWE(Country.ZIMBABWE,
            "Zimbabwe",
            "Zimbábue",
            "Zimbabue",
            "Zimbabwe",
            "Simbabwe",
            "Zimbabwe",
            "ジンバブエ",
            "짐바브웨 공화국",
            "津巴布韦",
            "Зимбабве",
            "زيمبابوي");

    private final Country country;
    private final String english;
    private final String portuguese;
    private final String spanish;
    private final String french;
    private final String german;
    private final String italian;
    private final String japanese;
    private final String korean;
    private final String chinese;
    private final String russian;
    private final String arabic;

    public static CountryTranslate fromCountry(Country country) {
        for (CountryTranslate translate : values()) {
            if (translate.country == country) {
                return translate;
            }
        }
        throw new IllegalArgumentException("Unknown country: " + country);
    }
}
