package com.negocil.negoturismo.admin.config.seeder.system;

import com.negocil.negoturismo.admin.feature.tour_guide.model.TouristAreaFile;
import com.negocil.negoturismo.admin.shared.document_file.model.DocumentFile;
import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum TouristAreaFileData {
    KALANDULA_1(TouristAreaFile.builder()
            .touristArea(TouristAreaData.KALANDULA.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Fkalandula%2F3.png?alt=media&token=bfced605-9cc5-457d-8c2b-54321503a00b")
                    .build())
            .build()),
    KALANDULA_2(TouristAreaFile.builder()
            .touristArea(TouristAreaData.KALANDULA.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Fkalandula%2F2.png?alt=media&token=706d28ca-f63d-48e6-b148-c4602847f23f")
                    .build())
            .build()),
    KALANDULA_3(TouristAreaFile.builder()
            .touristArea(TouristAreaData.KALANDULA.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Fkalandula%2F1.png?alt=media&token=58be226d-7bdc-461b-a9df-640ec3114896")
                    .build())
            .build()),
    TUNDAVALA_1(TouristAreaFile.builder()
            .touristArea(TouristAreaData.TUNDAVALA.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Ftundavala%2F2.png?alt=media&token=7e40936a-9262-4cea-a2e8-362301051c6a")
                    .build())
            .build()),
    AVENIDA_4_DE_FEVEREIRO_1(TouristAreaFile.builder()
            .touristArea(TouristAreaData.AVENIDA_4_DE_FEVEREIRO.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Favenida-4-de-fevereiro%2F1.png?alt=media&token=dcd2330f-b55b-4e60-aaa0-5d8d1569f7d5")
                    .build())
            .build()),
    AVENIDA_4_DE_FEVEREIRO_2(TouristAreaFile.builder()
            .touristArea(TouristAreaData.AVENIDA_4_DE_FEVEREIRO.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Favenida-4-de-fevereiro%2F2.png?alt=media&token=bf6e2437-a195-4fe3-ac6a-2e8b81917a92")
                    .build())
            .build()),
    AVENIDA_4_DE_FEVEREIRO_3(TouristAreaFile.builder()
            .touristArea(TouristAreaData.AVENIDA_4_DE_FEVEREIRO.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Favenida-4-de-fevereiro%2F3.png?alt=media&token=a95a04b7-c8c1-49bb-b780-a3dad2cffd67")
                    .build())
            .build()),
    ESTACAO_CENTRAL_DE_LUANDA_1(TouristAreaFile.builder()
            .touristArea(TouristAreaData.ESTACAO_CENTRAL_DE_LUANDA.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Festacao-ferro-de-luanda%2F1.png?alt=media&token=e700a950-a780-4dc8-9856-48ccd7306786")
                    .build())
            .build()),
    ESTACAO_CENTRAL_DE_LUANDA_2(TouristAreaFile.builder()
            .touristArea(TouristAreaData.ESTACAO_CENTRAL_DE_LUANDA.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Festacao-ferro-de-luanda%2F2.png?alt=media&token=166432b9-cc24-4108-9042-d6b344f48fb0")
                    .build())
            .build()),
    ESTACAO_CENTRAL_DE_LUANDA_3(TouristAreaFile.builder()
            .touristArea(TouristAreaData.ESTACAO_CENTRAL_DE_LUANDA.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Festacao-ferro-de-luanda%2F3.png?alt=media&token=620f650a-56ba-40c5-83b2-543eecb31a25")
                    .build())
            .build()),

    FORTALESA_DE_SAO_MIGUEL_1(TouristAreaFile.builder()
            .touristArea(TouristAreaData.FORTALESA_DE_SAO_MIGUEL.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Ffortaleza-sao-miguel%2F1.png?alt=media&token=47e34d23-e9dc-4361-96a0-a5b9abe99104")
                    .build())
            .build()),
    FORTALESA_DE_SAO_MIGUEL_2(TouristAreaFile.builder()
            .touristArea(TouristAreaData.FORTALESA_DE_SAO_MIGUEL.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Ffortaleza-sao-miguel%2F2.png?alt=media&token=ea57a6c5-85c5-439e-b3ad-f8bae9a84b82")
                    .build())
            .build()),
    FORTALESA_DE_SAO_MIGUEL_3(TouristAreaFile.builder()
            .touristArea(TouristAreaData.FORTALESA_DE_SAO_MIGUEL.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Ffortaleza-sao-miguel%2F3.png?alt=media&token=4e62dd0d-4e95-4d59-98ca-4972454e3547")
                    .build())
            .build()),

    IGREJA_DE_NOSSENHORA_DOS_REMEDIOS_1(TouristAreaFile.builder()
            .touristArea(TouristAreaData.IGREJA_DE_NOSSENHORA_DOS_REMEDIOS.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Figreja-nossa-senhora-remedios%2F1.png?alt=media&token=95e88c61-c5e8-4e62-ad4a-d9dc4d133b6d")
                    .build())
            .build()),
    IGREJA_DE_NOSSENHORA_DOS_REMEDIOS_2(TouristAreaFile.builder()
            .touristArea(TouristAreaData.IGREJA_DE_NOSSENHORA_DOS_REMEDIOS.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Figreja-nossa-senhora-remedios%2F2.png?alt=media&token=05d8edef-cd7b-46e0-bda6-82bde6209fd2")
                    .build())
            .build()),
    IGREJA_DE_NOSSENHORA_DOS_REMEDIOS_3(TouristAreaFile.builder()
            .touristArea(TouristAreaData.IGREJA_DE_NOSSENHORA_DOS_REMEDIOS.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Figreja-nossa-senhora-remedios%2F3.png?alt=media&token=507914e3-9449-4e20-8137-5bb2c6d6a4e4")
                    .build())
            .build()),

    MIRADOURO_DA_LUA_1(TouristAreaFile.builder()
            .touristArea(TouristAreaData.MIRADOURO_DA_LUA.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Fmirador-lua%2F1.png?alt=media&token=28eff5c2-0b77-446b-9b42-af7daddc03b1")
                    .build())
            .build()),
    MIRADOURO_DA_LUA_2(TouristAreaFile.builder()
            .touristArea(TouristAreaData.MIRADOURO_DA_LUA.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Fmirador-lua%2F2.png?alt=media&token=ddb03f44-7912-429a-82c2-9e404ab8244f")
                    .build())
            .build()),
    MIRADOURO_DA_LUA_3(TouristAreaFile.builder()
            .touristArea(TouristAreaData.MIRADOURO_DA_LUA.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Fmirador-lua%2F3.png?alt=media&token=8c730c4c-e1f9-406b-829f-abc2083bfaee")
                    .build())
            .build()),

    MONUMENTO_DO_SOLDADO_DESCONHECIDO_1(TouristAreaFile.builder()
            .touristArea(TouristAreaData.MONUMENTO_DO_SOLDADO_DESCONHECIDO.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Fmonumento-do-soldado-desconhecido%2F1.png?alt=media&token=aae6b16c-8c81-4fe8-b9a3-070007da137e")
                    .build())
            .build()),
    MONUMENTO_DO_SOLDADO_DESCONHECIDO_2(TouristAreaFile.builder()
            .touristArea(TouristAreaData.MONUMENTO_DO_SOLDADO_DESCONHECIDO.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Fmonumento-do-soldado-desconhecido%2F2.png?alt=media&token=bbaff755-272e-4944-b155-5374836b2376")
                    .build())
            .build()),
    MONUMENTO_DO_SOLDADO_DESCONHECIDO_3(TouristAreaFile.builder()
            .touristArea(TouristAreaData.MONUMENTO_DO_SOLDADO_DESCONHECIDO.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Fmonumento-do-soldado-desconhecido%2F3.png?alt=media&token=da206440-0ff4-4c85-ab93-6ddd0d3d59c8")
                    .build())
            .build()),

    MUSEU_OF_AGOSTHINO_NETO_1(TouristAreaFile.builder()
            .touristArea(TouristAreaData.MUSEU_OF_AGOSTHINO_NETO.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Fmuseu-agostinho-neto%2F1.png?alt=media&token=bc0073d8-3fe9-485b-8f55-edc7e8b7586c")
                    .build())
            .build()),
    MUSEU_OF_AGOSTHINO_NETO_2(TouristAreaFile.builder()
            .touristArea(TouristAreaData.MUSEU_OF_AGOSTHINO_NETO.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Fmuseu-agostinho-neto%2F2.png?alt=media&token=51636445-8a83-4037-88e9-a0bfd379d796")
                    .build())
            .build()),
    MUSEU_OF_AGOSTHINO_NETO_3(TouristAreaFile.builder()
            .touristArea(TouristAreaData.MUSEU_OF_AGOSTHINO_NETO.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Fmuseu-agostinho-neto%2F3.png?alt=media&token=a0efbcaf-c467-43cc-ae03-e42762b2f744")
                    .build())
            .build()),

    MUSEU_NACIONAL_DE_ANTROPOLOGIA_1(TouristAreaFile.builder()
            .touristArea(TouristAreaData.MUSEU_NACIONAL_DE_ANTROPOLOGIA.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Fmuseu-antropologia-angola%2F1.png?alt=media&token=227b9b98-1ff4-4456-bd23-13800cef0aa9")
                    .build())
            .build()),
    MUSEU_NACIONAL_DE_ANTROPOLOGIA_2(TouristAreaFile.builder()
            .touristArea(TouristAreaData.MUSEU_NACIONAL_DE_ANTROPOLOGIA.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Fmuseu-antropologia-angola%2F2.png?alt=media&token=16b682f6-f966-4fb5-b669-7ee089094408")
                    .build())
            .build()),
    MUSEU_NACIONAL_DE_ANTROPOLOGIA_3(TouristAreaFile.builder()
            .touristArea(TouristAreaData.MUSEU_NACIONAL_DE_ANTROPOLOGIA.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Fmuseu-antropologia-angola%2F3.png?alt=media&token=cc98504c-e102-4abd-b97b-44758002b8a1")
                    .build())
            .build()),

    MUSEU_NACIONAL_DA_ESCRAVATURA_1(TouristAreaFile.builder()
            .touristArea(TouristAreaData.MUSEU_NACIONAL_DA_ESCRAVATURA.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Fmuseu-escravatura%2F1.png?alt=media&token=2a3b0a32-8a23-4dd7-badf-fa803308bc05")
                    .build())
            .build()),
    MUSEU_NACIONAL_DA_ESCRAVATURA_2(TouristAreaFile.builder()
            .touristArea(TouristAreaData.MUSEU_NACIONAL_DA_ESCRAVATURA.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Fmuseu-escravatura%2F2.png?alt=media&token=9ac8e443-78de-43c0-ad25-0390b50e9b83")
                    .build())
            .build()),
    MUSEU_NACIONAL_DA_ESCRAVATURA_3(TouristAreaFile.builder()
            .touristArea(TouristAreaData.MUSEU_NACIONAL_DA_ESCRAVATURA.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Fmuseu-escravatura%2F3.png?alt=media&token=76fdd04b-862b-4763-a15f-5de0d89e947c")
                    .build())
            .build()),

    MUSEU_DA_MOEDA_1(TouristAreaFile.builder()
            .touristArea(TouristAreaData.MUSEU_DA_MOEDA.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Fmuseu-moeda%2F1.png?alt=media&token=1d50d3ec-6b70-4f93-8e3d-512e6db812e8")
                    .build())
            .build()),
    MUSEU_DA_MOEDA_2(TouristAreaFile.builder()
            .touristArea(TouristAreaData.MUSEU_DA_MOEDA.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Fmuseu-moeda%2F2.png?alt=media&token=92bc563c-3505-4140-8b06-83cec4c8b8fc")
                    .build())
            .build()),
    MUSEU_DA_MOEDA_3(TouristAreaFile.builder()
            .touristArea(TouristAreaData.MUSEU_DA_MOEDA.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Fmuseu-moeda%2F3.png?alt=media&token=28517e48-ad38-4cc8-8f8f-c941e6c8e3aa")
                    .build())
            .build()),

    ILHA_DO_MUSSULO_1(TouristAreaFile.builder()
            .touristArea(TouristAreaData.ILHA_DO_MUSSULO.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Fmussulo%2F1.png?alt=media&token=dbc20a41-34f3-4f36-b913-b009a40ebac9")
                    .build())
            .build()),
    ILHA_DO_MUSSULO_2(TouristAreaFile.builder()
            .touristArea(TouristAreaData.ILHA_DO_MUSSULO.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Fmussulo%2F2.png?alt=media&token=f30a6ed2-1ce2-407a-96a6-8c428d21a9da")
                    .build())
            .build()),
    ILHA_DO_MUSSULO_3(TouristAreaFile.builder()
            .touristArea(TouristAreaData.ILHA_DO_MUSSULO.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Fmussulo%2F3.png?alt=media&token=43fd23ce-ef07-49e1-9f28-455c947335ee")
                    .build())
            .build()),

    PALACIO_DE_FERRO_1(TouristAreaFile.builder()
            .touristArea(TouristAreaData.PALACIO_DE_FERRO.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Fpalacio-de-ferro%2F1.png?alt=media&token=1f33f940-03a7-47a3-80cf-a94f37d1bee5")
                    .build())
            .build()),
    PALACIO_DE_FERRO_2(TouristAreaFile.builder()
            .touristArea(TouristAreaData.PALACIO_DE_FERRO.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Fpalacio-de-ferro%2F2.png?alt=media&token=44a8efe2-e96c-4fe5-9d8e-d537ef269d13")
                    .build())
            .build()),
    PALACIO_DE_FERRO_3(TouristAreaFile.builder()
            .touristArea(TouristAreaData.PALACIO_DE_FERRO.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Fpalacio-de-ferro%2F3.png?alt=media&token=4b07f000-5461-44e1-b5c4-7f38b44b89d2")
                    .build())
            .build()),

    SANGANO_BEACH_1(TouristAreaFile.builder()
            .touristArea(TouristAreaData.SANGANO_BEACH.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Fsangano-beach%2F1.png?alt=media&token=fecbd639-5937-4699-9016-26bf1fbaa26f")
                    .build())
            .build()),
    SANGANO_BEACH_2(TouristAreaFile.builder()
            .touristArea(TouristAreaData.SANGANO_BEACH.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Fsangano-beach%2F2.png?alt=media&token=683cb09b-f416-403a-8c75-9182b247ec53")
                    .build())
            .build()),
    SANGANO_BEACH_3(TouristAreaFile.builder()
            .touristArea(TouristAreaData.SANGANO_BEACH.getTouristArea())
            .doc(DocumentFile.builder()
                    .url("https://firebasestorage.googleapis.com/v0/b/negoturismo-6d989.firebasestorage.app/o/tourism-area%2Fsangano-beach%2F3.png?alt=media&token=254ceffb-b6fd-4354-8809-bcef517e89aa")
                    .build())
            .build());

    private final TouristAreaFile touristAreaFile;
}
