package com.negocil.negoturismo.admin.shared.core.enums;

public final class PermissionCode {
    public static final String CREATE_USER = "CREATE_USER";
    public static final String UPDATE_USER = "UPDATE_USER";
    public static final String DELETE_USER = "DELETE_USER";
    public static final String READ_USER = "READ_USER";
    public static final String CREATE_CATEGORY = "CREATE_CATEGORY";
    public static final String UPDATE_CATEGORY = "UPDATE_CATEGORY";
    public static final String DELETE_CATEGORY = "DELETE_CATEGORY";
    public static final String READ_CATEGORY = "READ_CATEGORY";
    public static final String CREATE_ROLE = "CREATE_ROLE";
    public static final String UPDATE_ROLE = "UPDATE_ROLE";
    public static final String DELETE_ROLE = "DELETE_ROLE";
    public static final String READ_ROLE = "READ_ROLE";
    public static final String CREATE_PERMISSION = "CREATE_PERMISSION";
    public static final String UPDATE_PERMISSION = "UPDATE_PERMISSION";
    public static final String DELETE_PERMISSION = "DELETE_PERMISSION";
    public static final String READ_PERMISSION = "READ_PERMISSION";
    public static final String CREATE_ORGANIZATION = "CREATE_ORGANIZATION";
    public static final String UPDATE_ORGANIZATION = "UPDATE_ORGANIZATION";
    public static final String DELETE_ORGANIZATION = "DELETE_ORGANIZATION";
    public static final String READ_ORGANIZATION = "READ_ORGANIZATION";
    public static final String CREATE_PRODUCT = "CREATE_PRODUCT";
    public static final String UPDATE_PRODUCT = "UPDATE_PRODUCT";
    public static final String DELETE_PRODUCT = "DELETE_PRODUCT";
    public static final String READ_PRODUCT = "READ_PRODUCT";
    public static final String CREATE_INTERPRETER = "CREATE_INTERPRETER";
    public static final String UPDATE_INTERPRETER = "UPDATE_INTERPRETER";
    public static final String DELETE_INTERPRETER = "DELETE_INTERPRETER";
    public static final String READ_INTERPRETER = "READ_INTERPRETER";
    public static final String CREATE_TOUR_GUIDE = "CREATE_TOUR_GUIDE";
    public static final String UPDATE_TOUR_GUIDE = "UPDATE_TOUR_GUIDE";
    public static final String DELETE_TOUR_GUIDE = "DELETE_TOUR_GUIDE";
    public static final String READ_TOUR_GUIDE = "READ_TOUR_GUIDE";
    public static final String CREATE_TOURIST_AREA = "CREATE_TOURIST_AREA";
    public static final String UPDATE_TOURIST_AREA = "UPDATE_TOURIST_AREA";
    public static final String DELETE_TOURIST_AREA = "DELETE_TOURIST_AREA";
    public static final String READ_TOURIST_AREA = "READ_TOURIST_AREA";
    public static final String CREATE_ORGANIZATION_HIGHLIGHTS = "CREATE_ORGANIZATION_HIGHLIGHTS";
    public static final String UPDATE_ORGANIZATION_HIGHLIGHTS = "UPDATE_ORGANIZATION_HIGHLIGHTS";
    public static final String DELETE_ORGANIZATION_HIGHLIGHTS = "DELETE_ORGANIZATION_HIGHLIGHTS";
    public static final String READ_ORGANIZATION_HIGHLIGHTS = "READ_ORGANIZATION_HIGHLIGHTS";
    public static final String CREATE_PRODUCT_PROMOTION = "CREATE_PRODUCT_PROMOTION";
    public static final String UPDATE_PRODUCT_PROMOTION = "UPDATE_PRODUCT_PROMOTION";
    public static final String DELETE_PRODUCT_PROMOTION = "DELETE_PRODUCT_PROMOTION";
    public static final String READ_PRODUCT_PROMOTION = "READ_PRODUCT_PROMOTION";
}